### ISSUE TITLE
r2s runs with `source.h5m` for subvoxel r2s without error message

### ISSUE THREAD

**Issue by zxkjack123** [pyne/pyne#1016]
PyNE can perform both r2s and subvoxel r2s now. When I was calculating a simple geometry with  both r2s and subvoxel r2s, I mistook the 'source.h5m' file (using 'source.h5m' produced for subvoxel r2s to do the normal r2s calculation).  Then r2s photon transport ran without error message, but produced a wrong result. It's hard for user to realize that they get a wrong result. 
A check should be added to prevent this mistake of 'source.h5m' happens, and there should be a proper error message to help users notice the problem.

**Comment by zxkjack123** [comment]
I made a PR to fix this problem. See PR #1017 .

**Comment by zxkjack123** [comment]
After applying the #1017, when users run DEFAULT r2s with a `source.h5m` file that produced by a SUBVOXEL r2s process, there is an error message and the program aborted successfully. 
Below is an example message of that unsupported user behavior:
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  The source.h5m contains cell_fracs tag. Wrong source.h5m file used.

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7F4DEC40AE08
#1  0x7F4DEC409F90
#2  0x7F4DEA5264AF
#3  0x7F4DEA526428
#4  0x7F4DEA528029
#5  0x7F4DEAB6084C
#6  0x7F4DEAB5E6B5
#7  0x7F4DEAB5E700
#8  0x7F4DEAB5E918
#9  0x57866B in pyne::Sampler::mesh_tag_data(moab::Range, std::vector<double, std::allocator<double> >)
#10  0x5797A2 in pyne::Sampler::setup()
#11  0x579B19 in pyne::Sampler::Sampler(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<double, std::allocator<double> >, bool)
#12  0x57BB6A in sampling_setup_
#13  0x45E785 in source_
#14  0x53BD54 in startp_
#15  0x418C78 in hstory_
#16  0x429F02 in trnspt_
#17  0x509BDC in mcrun_
#18  0x41D7AD in MAIN__ at main.F90:?
Aborted (core dumped)
```

As the check code in #1017 works as expected (terminate the program and give an error message), close this issue.
