### ISSUE TITLE
ENDF reader issue [bug]

### ISSUE THREAD

**Issue by KennellyT** [pyne/pyne#1050]
When running the ENDF reader [tutorial](http://pyne.io/examples/endf_reader.html), I receive this error: 
`u235.get_xs(922350000,16)`

/home/tyler/spont_fiss/untitled1.py:1: DeprecationWarning: 'U' mode is deprecated
  #!/usr/bin/env python3
Traceback (most recent call last):
  File "<ipython-input-6-72c736b7f799>", line 1, in <module>
    u235.get_xs(922350000,16)

  File "endf.pyx", line 1007, in pyne.endf.Library.get_xs

  File "endf.pyx", line 598, in pyne.endf.Library._read_res

IndexError: index 0 is out of bounds for axis 0 with size 0

It seems that get_xs or _read_res is the cause of the error. I will further investigate.

**Comment by scopatz** [comment]
Thanks for reporting @KennellyT!

**Comment by gonuke** [comment]
This is resolved by #1298
