### ISSUE TITLE
HTTP Error for grabbing http://data.pyne.io/kaeri.zip

### ISSUE THREAD

**Issue by ASamarkRoth** [pyne/pyne#1060]
I tried building the nuclear data by:

`./nuc_data_make --fetch-prebuilt false`

I obtained: 

```
Grabbing neutron summary files from KAERI
  grabbing http://data.pyne.io/kaeri.zip and placing it in build_nuc_data/kaeri.zip
Traceback (most recent call last):
  File "./nuc_data_make", line 6, in <module>
    main()
  File "/home/anton/anaconda3/lib/python3.6/site-packages/pyne/dbgen/nuc_data_make.py", line 157, in main
    make_map[mo](args)
  File "/home/anton/anaconda3/lib/python3.6/site-packages/pyne/dbgen/simple_xs.py", line 265, in make_simple_xs
    grab_kaeri_simple_xs(build_dir)
  File "/home/anton/anaconda3/lib/python3.6/site-packages/pyne/dbgen/simple_xs.py", line 36, in grab_kaeri_simple_xs
    urllib.urlretrieve(zip_url, zip_path)
  File "/home/anton/anaconda3/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/anton/anaconda3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/anton/anaconda3/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/anton/anaconda3/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/anton/anaconda3/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/anton/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/anton/anaconda3/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

The link seems to be down.

**Comment by pshriwise** [comment]
Has there been any movement on this? I'm currently unable to get any files from the data.pyne.io server.

**Comment by gonuke** [comment]
I think data.pyne.io is gone for ever - not sure where it is/was...  Could look at Rackspace images for `nemo` and `sheeple`?

**Comment by gonuke** [comment]
If we can't find the data, we need to change all the references to those files.

**Comment by gonuke** [comment]
Closing in favor of #1255
