### ISSUE TITLE
Installing Pyne with conda problem

### ISSUE THREAD

**Issue by kyfranzen** [pyne/pyne#1190]
After installing PyNE with conda I got the following error when running r2s.py setup:

pyne-env) [ken@attila r2s_run]$ python r2s.py setup
Traceback (most recent call last):
  File "r2s.py", line 3, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
(pyne-env) [ken@attila r2s_run]$ python2 r2s.py setup
Traceback (most recent call last):
  File "r2s.py", line 6, in <module>
    from pyne.mesh import Mesh
ImportError: No module named pyne.mesh
(pyne-env) [ken@attila r2s_run]$

Do you have any workarounds?

Thanks,
Ken

**Comment by gonuke** [comment]
I think the short answer is that conda support for pyne is out of date, particularly for use in R2S workflows.

We do have a repository with [installation scripts](https://github.com/pyne/install_scripts) that might help you build from source.

**Comment by gonuke** [comment]
P.S. the [pyne-dev](https://groups.google.com/forum/#!forum/pyne-dev) and/or [pyne-users](https://groups.google.com/forum/#!forum/pyne-users) mailing list may be better places for this kind of question

**Comment by kyfranzen** [comment]
Thanks, I will try that option.

**Comment by gonuke** [comment]
This will be fully resolved when moab & dagmc support are in the conda-forge build. (#1250)
