### ISSUE TITLE
PyNE not working in OSX virtualenv

### ISSUE THREAD

**Issue by murphy-jw** [pyne/pyne#1235]
Hello,  
I have created a Python 2.7 virtualenv, installed the dependencies, and then successfully built from source, however, after building I am not able to run nuc_data_make or import pyne in python. If I try I get the following error:  

```
(pynethon) seatac5:pyne murphy70$ nuc_data_make 
/Users/murphy70/pynethon/lib/python2.7/site-packages/pyne/__init__.py:18: Warning: Error importing PyNE: you should not try to import PyNE from its source directory; please exit the PyNE source tree, and relaunch your python interpreter from there.
  warn(msg, Warning)
Traceback (most recent call last):
  File "/Users/murphy70/pynethon/bin/nuc_data_make", line 4, in <module>
    from pyne.dbgen.nuc_data_make import main
  File "/Users/murphy70/pynethon/lib/python2.7/site-packages/pyne/__init__.py", line 13, in <module>
    from .pyne_config import *
ImportError: dlopen(/Users/murphy70/pynethon/lib/python2.7/site-packages/pyne/pyne_config.so, 2): Library not loaded: @rpath/libpyne.dylib
  Referenced from: /Users/murphy70/pynethon/lib/python2.7/site-packages/pyne/pyne_config.so
  Reason: image not found
```

This error happens no matter if I try to run the nuc_data_make from within the build directory or not. One thing that may be causing an issue is that I have cloned pyne inside my virtualenv folder, which is /Users/murphy70/pynethon.

**Comment by katyhuff** [comment]
When you cloned pyne into your virtualenv folder, did you do it with git, or by copy-pasting something from a Linux machine? The reason I ask is that there is a distinction between the filenames built on macosx (.dylib) and Linux (.so).  It seems you have a `.so` file (pyne_config.so) that likely wasn't built on your mac, but was rather generated elsewhere... 

FWIW, I have a source-built pyne working on my mac, but I use conda environments (not virtualenv)... so it's also possible that it's breaking because of virtualenv.

**Comment by murphy-jw** [comment]
No, I cloned it from my terminal on OSX. Not sure if I had virtualenv activated when I cloned, but I believe that I did, if that makes a difference. Going to try to install via macports now.

Edit: Macports didn't work either:  

```
 _                        )      ((   ))     (                          
(@)                      /|\      ))_((     /|\                          
|-|                     / | \    (/\|/\)   / | \                      (@) 
| | -------------------/--|-voV---\`|'/--Vov-|--\---------------------|-|
|-|                         '^`   (o o)  '^`                          | |
| |                               `\Y/'                               |-|
|-|                                                                   | |
| |        /\             ___           __  __             /\         |-|
|-|       /^~\           / _ \_   _  /\ \ \/__\           /^~\        | |  
| |       /^~\          / /_)/ | | |/  \/ /_\             /^~\        |-|
|-|       /^~\         / ___/| |_| / /\  //__             /^~\        | | 
| |       ^||`         \/     \__, \_\ \/\__/             ^||`        |-|  
|-|        ||                |____/                        ||         | | 
| |       ====                                            ====        |-|
|-|                                                                   | |
| |                                                                   |-|
|-|___________________________________________________________________| |
(@)              l   /\ /         ( (       \ /\   l                `\|-|
                 l /   V           \ \       V   \ l                  (@)
                 l/                _) )_          \I                   
                                   `\ /'
                                     `  

Making nuc_data at /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyne/nuc_data.h5
Copying AME 2012 atomic mass data.
Making atomic mass data table.
Traceback (most recent call last):
  File "/opt/local/bin/nuc_data_make-2.7", line 6, in <module>
    main()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyne/dbgen/nuc_data_make.py", line 155, in main
    make_map[mo](args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyne/dbgen/atomic_mass.py", line 155, in make_atomic_mass
    make_atomic_mass_table(nuc_data, build_dir)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyne/dbgen/atomic_mass.py", line 123, in make_atomic_mass_table
    kdb = tb.openFile(nuc_data, 'a', filters=BASIC_FILTERS)
AttributeError: 'module' object has no attribute 'openFile'
```

**Comment by katyhuff** [comment]
Ah, I would not have recommended adding another python in this case. When you say you tried to install via macports, do you mean you installed a new python, or do you mean you tried installing pyne via macports?

Please note, my original question was about cloning pyne. I should ask specifically : did you use `git clone`? (I recognize all of this is happening in the terminal.)

Can you share the output of the history command?

**Comment by murphy-jw** [comment]
I did have to install another version of python (2.7.8) using macports, and some dependencies. Sorry for diversion.

Back to original question - yes, I used `git clone` to get the source code. I don't have the output of the history anymore beyond what I've already shared. 

For the time being I switched to openmc, which I was able to compile, as I am immediately just looking for a way to query and visualize x-section data. 

I would like to be able to use PyNE though. I originally tried to install via anaconda, but it failed initially because it said PyNE was not compatible with Python3.7, but even after switching to my Anaconda installation to Python3.6 it would just fail to "find a solution" when trying to install, which is why I went to try and build from source. I'd be glad to try again if you have suggestions about how to install via either conda or building from source (in terms of python version to use, virtualenv or no, or other things that might not be mentioned in the README).

**Comment by bam241** [comment]
I am not sure it is helpful, but I just successfully compiled using `macport` and `Python` `3.6.9` an ran `nuc_data_make`
what I did is:
from `PyNE` source folder
```
git fetch --all
git checkout develop
git rebase upstream/develop
```
just to be sure I ran the last version version of PyNE develop
```
python setup.py install --clean --user
cd
nuc_data_make
```
You might have to update your $PYTHONPATH and $PATH to have both the lib and the script found properly...
Hope this helps.

The actual `conda` `PyNE` package is actually super outdated (like 3-5years)... so no surprise there (we are working on releasing a new package soon)
On solution with Anaconda, would be to use conda to install the dependencies and then compile from source (don't see why this would not work...)


We seems to have the same kind of system (Mac users are not that frequent in PyNE world), so let me know if you need further help.

**Comment by katyhuff** [comment]
Yeah, I'll confirm what Baptiste has said. This is what works on my mac:

>  use conda to install the dependencies and then compile from source
