### ISSUE TITLE
MOAB 5.2.0 compatibility

### ISSUE THREAD

**Issue by bam241** [pyne/pyne#1325]
We are facing an Incompatibility with MOAB 5.2.0

when running the test when PyNE built against MOAB 5.2.0 we got:
```
>> alara alara_inp > output.txt
/usr/bin/h5diff
/root/.local/lib/python3.6/site-packages/pyne/alara.py:1063: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  (response_name, np.float64, data_length)
Writing decay_heat for decay time: 1E3 s
Activation_response step2 complete.
attribute: <default of </tstt/tags/GLOBAL_ID>> and <default of </tstt/tags/GLOBAL_ID>>
1 differences found
F
======================================================================
FAIL: test_activation_responses.test_activation_responses_script
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/pyne/tests/test_activation_responses.py", line 270, in test_activation_responses_script
    _activation_responses_test_step2(activation_responses_run_dir)
  File "/opt/pyne/tests/test_activation_responses.py", line 257, in _activation_responses_test_step2
    assert_equal(diff_flag5, 0)
AssertionError: 256 != 0

----------------------------------------------------------------------
Ran 4 tests in 1.889s

FAILED (failures=1)
```

**Comment by gonuke** [comment]
This has been resolved by #1328
