### ISSUE TITLE
Error when running nuc_data_make: AttributeError: 'numpy.int64' object has no attribute 'complib'

### ISSUE THREAD

**Issue by ljacobson64** [pyne/pyne#1363]
**Describe the Bug**

I'm getting the following error message when running `nuc_data_make`:

```
Fetching pre-built nuc_data.h5 from https://github.com/pyne/data/raw/master/prebuilt_nuc_data.h5
Making nuc_data at /opt/software_native/pyne/lib/python3.8/site-packages/pyne/nuc_data.h5
skipping atomic mass data table creation; already exists.
skipping scattering lengths data table creation; already exists.
skipping ENSDF decay data table creation; already exists.
skipping simple XS data table creation; already exists.
Grabbing cinder.dat from /opt/software_misc/MCNP/MCNP_DATA
cinder.dat contains export controlled information nuc_data.h5 is now export controlled!
Adding cinder data...
  energy group boundaries.
  neutron absorption cross sections.
Traceback (most recent call last):
  File "/opt/software_native/pyne/bin/nuc_data_make", line 6, in <module>
    main()
  File "/opt/software_native/pyne/lib/python3.8/site-packages/pyne/dbgen/nuc_data_make.py", line 156, in main
    make_map[mo](args)
  File "/opt/software_native/pyne/lib/python3.8/site-packages/pyne/dbgen/cinder.py", line 855, in make_cinder
    make_mg_absorption(nuc_data, build_dir)
  File "/opt/software_native/pyne/lib/python3.8/site-packages/pyne/dbgen/cinder.py", line 226, in make_mg_absorption
    absorption_table = db.create_table('/neutron/cinder_xs/', 'absorption',
  File "/usr/lib/python3/dist-packages/tables/file.py", line 1053, in create_table
    ptobj = Table(parentnode, name,
  File "/usr/lib/python3/dist-packages/tables/table.py", line 835, in __init__
    super(Table, self).__init__(parentnode, name, new, filters,
  File "/usr/lib/python3/dist-packages/tables/leaf.py", line 286, in __init__
    super(Leaf, self).__init__(parentnode, name, _log)
  File "/usr/lib/python3/dist-packages/tables/node.py", line 264, in __init__
    self._v_objectid = self._g_create()
  File "/usr/lib/python3/dist-packages/tables/table.py", line 1023, in _g_create
    self._v_new_title, self.filters.complib or '', obversion)
AttributeError: 'numpy.int64' object has no attribute 'complib'
Closing remaining open files:/opt/software_native/pyne/lib/python3.8/site-packages/pyne/nuc_data.h5...done
```

**To Reproduce**

Run `nuc_data_make`

**System information**

 - OS: Ubuntu 20.04
 - PyNE Version: develop
 - Versions of dependencies installed with: HDF5 1.10.7, MOAB 5.2.0, DAGMC develop

**Comment by ljacobson64** [comment]
I'm still seeing this error. Does anyone know what might cause this?

**Comment by ahnaf-tahmid-chowdhury** [comment]
Hi @ljacobson64, my apologies for the delayed response. I believe the issue was caused by using different versions of `numpy`. Nevertheless, I'm glad to inform you that the problem has been resolved now. If you encounter any further issues with the latest version of PyNE, please don't hesitate to reach out to us. We're here to help!

**Comment by gonuke** [comment]
This issue may persist if running `nuc_data_make` with a `CINDER.DAT` file - something that not everyone has access to.

**Comment by gonuke** [comment]
I think this is because the prebuilt data that we provide in our [data archive](github.com/pyne/data) was produced before we added compression to the standard format.  We'll need to produce a new copy of the prebuilt data from scratch and it should work.

**Comment by gonuke** [comment]
I'm not sure how long it's been since someone tried to/was able to build this data from scratch because most just use the prebuilt data

**Comment by gonuke** [comment]
I think the error only occurs when trying to add data to the file

**Comment by gonuke** [comment]
This was discovered by loading the prebuilt data with pytables and printing the `Filters`

```
import tables as tb
data_file = tb.open_file('prebuilt_nuc_data.h5')
print(data_file.filters)
print(pyne.api.BASIC_FILTERS)
```

**Comment by ahnaf-tahmid-chowdhury** [comment]
it seems [data archive](https://github.com/pyne/pyne/issues/github.com/pyne/data) is broken. I am unable to access this.

```console
Fetching pre-built nuc_data.h5 from https://github.com/pyne/data/raw/master/prebuilt_nuc_data.h5
Making nuc_data at /opt/nuclear-boy/lib/python3.11/site-packages/pyne-0.7.7-py3.11.egg/pyne/nuc_data.h5
skipping atomic mass data table creation; already exists.
skipping scattering lengths data table creation; already exists.
skipping ENSDF decay data table creation; already exists.
skipping simple XS data table creation; already exists.
DATAPATH not defined in environment; cinder.dat not found - skipping.
skipping materials library data table creation; already exists.
skipping q_value table creation; already exists.
skipping creation of dose factor tables; already exists.
skipping EAF activation data table creation; already exists.
skipping WIMSD fission product yield table creation; already exists.
skipping NDS fission product yield table creation; already exists.
```

In my case, it is showing `cinder.dat` not found.

I have also tried to check the basic filters of pyne:

```python
Python 3.11.2 (main, May 30 2023, 17:45:26) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tables as tb
>>> data_file = tb.open_file('prebuilt_nuc_data.h5')
>>> print(data_file.filters)
Filters(complevel=0, shuffle=False, bitshuffle=False, fletcher32=False, least_significant_digit=None)
>>> import pyne
>>> print(pyne.api.BASIC_FILTERS)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyne' has no attribute 'api'
>>> from pyne import api
>>> print(api.BASIC_FILTERS)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyne.api' has no attribute 'BASIC_FILTERS'
```

Since complevel=0, it suggests that the data is not compressed. If we are facing issues with compatibility due to compression differences, this could be the reason. The `nuc_data_make` script might have been updated to include data compression (complevel > 0), which could cause compatibility problems with the older uncompressed data.

**Comment by ahnaf-tahmid-chowdhury** [comment]
```python
import tables as tb
from pyne.api import nuc_data
data_file = tb.open_file('prebuilt_nuc_data.h5')
print(data_file.filters)
data_file2 = tb.open_file(nuc_data)
print(data_file2.filters)
```
```console
Filters(complevel=0, shuffle=False, bitshuffle=False, fletcher32=False, least_significant_digit=None)
Filters(complevel=0, shuffle=False, bitshuffle=False, fletcher32=False, least_significant_digit=None)
```
Oh, It seems both are same!

**Comment by gonuke** [comment]
Your `nuc_data` is derived from the prebuilt data, and thus has the same filters.  

It should be possible to make a clean version with some options to `nuc_data_make`, but that may fail for other reasons (I'll try soon hopefully)

`CINDER.DAT` is an export controlled file that is not shared by our data source.

**Comment by ljacobson64** [comment]
Just tested -- I still get the same error if I have the DATAPATH variable set to the location of my MCNP data, but the error does not appear if I clear the DATAPATH variable.

I'm not sure what data is present in `cinder.dat`, so I don't think not having it be part of my pyne data is going to be a problem for me.

I'll also mention that I had to fix 2 general pyne build errors before I could even test this. The first error was that it was looking for `f2py` in `/usr/bin` instead of `$HOME/.local/bin`, so I had to use `--deps-root $HOME/.local` to fix it. The second error was that I was getting weird Cython errors which I was only able to fix by downgrading my version of Cython from 3.0.0 to 0.29.36. Is it worth me making an issue about these other build problems?
