### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by mboisson** [pyne/pyne#1383]
With the very latest version of PyNE (https://github.com/pyne/pyne/archive/refs/tags/0.7.3.tar.gz), I get the following error, which seems to be the same issue as
 https://github.com/pyne/pyne/issues/1340

This is supposed to be fixed already, according to the other issue, but I still run into this. 
```
    /tmp/pip-req-build-rlkdn2o9/build/pyne/transmuters.cxx: In function ‘PyObject* __pyx_pf_4pyne_11transmuters_cram(PyObject*, PyObject*, PyObject*, int)’:
    /tmp/pip-req-build-rlkdn2o9/build/pyne/transmuters.cxx:2840:70: error: ‘__pyx_builtin_ValueError’ was not declared in this scope; did you mean ‘__pyx_builtin_ImportError’?
     2840 |     try { throw; } catch(const std::exception& exn) {PyErr_SetString(__pyx_builtin_ValueError, exn.what());} catch(...) { PyErr_SetNone(__pyx_builtin_ValueError); }
          |                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~
          |                                                                      __pyx_builtin_ImportError
    /tmp/pip-req-build-rlkdn2o9/build/pyne/transmuters.cxx:2840:137: error: ‘__pyx_builtin_ValueError’ was not declared in this scope; did you mean ‘__pyx_builtin_ImportError’?
     2840 |     try { throw; } catch(const std::exception& exn) {PyErr_SetString(__pyx_builtin_ValueError, exn.what());} catch(...) { PyErr_SetNone(__pyx_builtin_ValueError); }
          |                                                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~
          |                                                                                                                                         __pyx_builtin_ImportError
    make[2]: *** [pyne/CMakeFiles/transmuters.dir/build.make:69: pyne/CMakeFiles/transmuters.dir/transmuters.cxx.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:1008: pyne/CMakeFiles/transmuters.dir/all] Error 2
    make: *** [Makefile:130: all] Error 2
    /tmp/pip-req-build-rlkdn2o9/setup.py:38: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      import imp
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-rlkdn2o9/setup.py", line 420, in <module>
        main()
      File "/tmp/pip-req-build-rlkdn2o9/setup.py", line 404, in main
        main_safe(ns)
      File "/tmp/pip-req-build-rlkdn2o9/setup.py", line 396, in main_safe
        main_body(ns)
      File "/tmp/pip-req-build-rlkdn2o9/setup.py", line 379, in main_body
        rtn = subprocess.check_call(['make'] + ns.make_args, cwd=ns.build_dir)
      File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.7.9/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
    Writing atomic_data.h
    Writing atomic_data.cpp
    CMake command is
    cmake .. -DCMAKE_INSTALL_PREFIX=/home/mboisson/wheels/tmp.31036/build_python-3.7 -DENABLE_SPATIAL_SOLVERS=ON -DPYTHON_EXECUTABLE=/home/mboisson/wheels/tmp.31036/build_python-3.7/bin/python

    --------------------

    If you are having issues building pyne, please report your problem to pyne-dev@googlegroups.com or look for help at http://pyne.io
```

**Comment by mboisson** [comment]
I have the following versions of packages: 
HDF5: 1.10.6
h5py==3.1.0
Jinja2==2.11.2
numpy==1.19.2
Cython==0.29.21

**Comment by bam241** [comment]
it was not fixed yet in 0.7.3, but more recently and sadly we haven't issued a release since.

the best option is probably to either to get the last develop from GitHub (`git clone --single-branch --branch develop https://github.com/pyne/pyne`), or to apply the modification your self (https://github.com/pyne/pyne/pull/1362/files),
 the modification are quite simple:
you'll only need to take out the 2 `ValueError` from file `pyne/cpp_transmuters.pxd` (line 8 and line 9)

(in the mean time, I'll work at the quick release with that fix included. @gonuke @pshriwise ...)

**Comment by mboisson** [comment]
Thanks. Installing from the git develop branch is a big no-no for us. Any ETA on the new release ? If it is less than a few days, I'll wait, otherwise I'll see to apply the patch and build the patched wheel for our users.

**Comment by mboisson** [comment]
I ended up applying the patch.
