### ISSUE TITLE
Problem with build PyNE

### ISSUE THREAD

**Issue by osamamala** [pyne/pyne#1457]
Hello)
**Describe the Bug**<br/>
After installing the latest version of Anaconda (Anaconda3-2022.05-Linux-x86_64.sh) I stuck with installing Pyne from anaconda. 

I used the following command:

`conda install -c conda-forge pyne`

I also used the [ubuntu.sh] script provided here (https://github.com/pyne/install_scripts/blob/main/ubuntu.sh)
https://alexmalins.com/blog/installing-pyne-on-windows-via-wsl/
which build PyNE by 

`python setup.py install --user`

Unfortunately, neither method worked!

I got this error message when I use the `conda install -c conda-forge pyne`:
```
bashCollecting package metadata (current_repodata.jsonfailed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 87, in _main
        exit_code = do_call(args, p)
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/cli/install.py", line 260, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 195, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 300, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 463, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 1058, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/core/index.py", line 291, in get_reduced_index
        push_record(record)
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/core/index.py", line 265, in push_record
        combined_depends = record.combined_depends
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/models/records.py", line 340, in combined_depends
        result = {ms.name: ms for ms in MatchSpec.merge(self.depends)}
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 478, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 478, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 509, in _merge
        final = this_component.merge(that_component)
      File "/home/Osamamala/anaconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 760, in merge
        raise ValueError("Incompatible component merge:\n  - %r\n  - %r"
    ValueError: Incompatible component merge:
      - 'mpi_openmpi_*'
      - 'mpi_openmpi_tempest*'

`$ /home/Osamamala/anaconda3/bin/conda install -c conda-forge pyne`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/Osamamala/anaconda3/bin/conda
             CONDA_PREFIX=/home/Osamamala/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/Osamamala/anaconda3/bin/python
               CONDA_ROOT=/home/Osamamala/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/Osamamala/anaconda3/bin:/home/Osamamala/anaconda3/bin:/home/Osam
                          amala/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr
                          /bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/System32:/m
                          nt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/Wind
                          owsPowerShell/v1.0:/mnt/c/Users/OsamaAbdelaziz/AppData/Local/Microsoft
                          /WindowsApps
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/Osamamala/anaconda3
            shell level : 1
       user config file : /home/Osamamala/.condarc
 populated config files :
          conda version : 4.12.0
    conda-build version : 3.21.8
         python version : 3.9.12.final.0
       virtual packages : __linux=4.4.0=0
                          __glibc=2.23=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/Osamamala/anaconda3  (writable)
      conda av data dir : /home/Osamamala/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/Osamamala/anaconda3/pkgs
                          /home/Osamamala/.conda/pkgs
       envs directories : /home/Osamamala/anaconda3/envs
                          /home/Osamamala/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Linux/4.4.0-43-Microsoft ubuntu/16.04.2 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:
Timeout reached. No report sent.
```

and this error when I used the [ubuntu.sh] script:

```
(base) Osamamala@DESKTOP-MJLLOMG:~/pyne-0.7.7$ python setup.py install --user
/home/Osamamala/pyne-0.7.7/setup.py:38: DeprecationWarning: the imp module is deprecated in favour of importlib; see the
 module's documentation for alternative uses
  import imp
Writing atomic_data.h
Writing atomic_data.cpp
/usr/bin/cmake
CMake command is
cmake .. -DCMAKE_INSTALL_PREFIX=/home/Osamamala/.local -DENABLE_SPATIAL_SOLVERS=ON -DPYTHON_EXECUTABLE=/home/Osamamala/a
naconda3/bin/python
CMake Error at CMakeLists.txt:4 (if):
  if given arguments:

    "3.5.1" "VERSION_GREATER_EQUAL" "3.12.0"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!

--------------------

If you are having issues building pyne, please report your problem to pyne-dev@googlegroups.com or look for help at http
://pyne.io

--------------------
Traceback (most recent call last):
  File "/home/Osamamala/pyne-0.7.7/setup.py", line 481, in <module>
    main()
  File "/home/Osamamala/pyne-0.7.7/setup.py", line 464, in main
    main_safe(ns)
  File "/home/Osamamala/pyne-0.7.7/setup.py", line 456, in main_safe
    main_body(ns)
  File "/home/Osamamala/pyne-0.7.7/setup.py", line 437, in main_body
    rtn = subprocess.check_call(cmake_cmd, cwd=ns.build_dir, shell=IS_NT)
  File "/home/Osamamala/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '..', '-DCMAKE_INSTALL_PREFIX=/home/Osamamala/.local', '-DENABLE_SPATI
AL_SOLVERS=ON', '-DPYTHON_EXECUTABLE=/home/Osamamala/anaconda3/bin/python']' returned non-zero exit status 1.
(base) Osamamala@DESKTOP-MJLLOMG:~/pyne-0.7.7$
```

**Please complete the following information regarding your system:**<br/>
 - OS: 
[ubuntu Linux 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial]
 - PyNE Version:  [e.g. 0.7.7]

**Additional Context**<br/>
What do I need to install PyNE
Thanks in advance
Osama

**Comment by osamamala** [comment]
Upgrading the Linux subsystem from 16.04 to 18.04, then installing anaconda, and finally, run `ubuntu.sh` script from [](https://github.com/pyne/install_scripts will) solve the problem. 

Osama
osamamala@yahoo.com

**Comment by gonuke** [comment]
Thanks for your persistence and sharing your solution @osamamala !
