### ISSUE TITLE
PyNE fails to install on Mac due to architecture incompatibility issues

### ISSUE THREAD

**Issue by sudo-nano** [pyne/pyne#1464]
**Describe the Bug**<br/>
PyNE builds properly, but will not install on my M1 Macbook Air. The error message: 

`ImportError: dlopen(/Users/cwg1231/Downloads/pyne-0.7.7/build/pyne/pyne_config.so, 0x0002): tried: '/Users/cwg1231/Downloads/pyne-0.7.7/build/pyne/pyne_config.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/pyne_config.so' (no such file), '/usr/lib/pyne_config.so' (no such file)`

describes that the architecture of pyne_config.so is incompatible. 

**To Reproduce**<br/>
`sudo python3 setup.py --slow -j 8 build` (completes successfully)
`sudo python3 setup.py install` (fails with aforementioned error)

**Expected Behavior**<br/>
PyNE builds and installs without incident.

**Screenshots or Code Snippets**<br/>
<details>
    <summary>Paste of entire terminal output when installing</summary>

```
/Users/cwg1231/Downloads/pyne-0.7.7/setup.py:38: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
atomic_data.h generated is the same as existing file, skipping.
atomic_data.cpp generated is the same as existing file, skipping.
/opt/homebrew/bin/cmake
CMake command is
cmake .. -DCMAKE_INSTALL_PREFIX=/Users/cwg1231/opt/anaconda3 -DENABLE_SPATIAL_SOLVERS=ON -DPYTHON_EXECUTABLE=/Users/cwg1231/opt/anaconda3/bin/python3

                                  /   \       
                          )      ((   ))     (                          
(@)                      /|\      ))_((     /|\                          
|-|                     / | \    (/\|/\)   / | \                      (@) 
| | -------------------/--|-voV---\`|'/--Vov-|--\---------------------|-|
|-|                         '^`   (o o)  '^`                          | |
| |                               `\Y/'                               |-|
|-|                                                                   | |
| |        /\             ___           __  __             /\         |-|
|-|       /^~\           / _ \_   _  /\ \ \/__\           /^~\        | |  
| |       /^~\          / /_)/ | | |/  \/ /_\             /^~\        |-|
|-|       /^~\         / ___/| |_| / /\  //__             /^~\        | | 
| |       ^||`         \/     \__, \_\ \/\__/             ^||`        |-|  
|-|        ||                |____/                        ||         | | 
| |       ====                                            ====        |-|
|-|                                                                   | |
| |                                                                   |-|
|-|___________________________________________________________________| |
(@)              l   /\ /         ( (       \ /\   l                `\|-|
                 l /   V           \ \       V   \ l                  (@)
                 l/                _) )_          \I                   
                                   `\ /'
                                     `  


-- Pyne platform defined as: __APPLE__
-- Checking whether to build spatial solvers
-- -- Checking CMAKE_CXX_COMPILER_ID: AppleClang
-- Build spatial solvers: false
-- Build type: Release
-- PyNE Fast Compile: FALSE
-- CMAKE_INSTALL_RPATH: /Users/cwg1231/opt/anaconda3/lib:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
-- CMake Install Prefix: /Users/cwg1231/opt/anaconda3
-- Dependency Root Dir (DEPS_ROOT_DIR): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr
-- Dependency Hints (DEPS_HINTS): HINTS;/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr
-- Dependency Binary Hints (DEPS_BIN_HINTS): HINTS;/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr;/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
-- Dependency Library Hints (DEPS_LIB_HINTS): HINTS;/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr;/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
-- Dependency Include Hints (DEPS_INCLUDE_HINTS): HINTS;/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
-- HDF5 Root: 
-- HDF5 C compiler wrapper is unable to compile a minimal HDF5 program.
--    HDF5 Include directory: /opt/homebrew/include
--    HDF5 Library directories: 
--    HDF5 Libraries: /opt/homebrew/lib/libhdf5.dylib
--    HDF5 library version: 1.12.2
-- PYTHON_EXECUTABLE: /Users/cwg1231/opt/anaconda3/bin/python3
-- PYTHON_SITE_PACKAGES: /Users/cwg1231/opt/anaconda3/lib/python3.9/site-packages
-- NUMPY_VERSION_STRING = 1.21.5
-- CMAKE_Fortran_IMPLICIT_LINK_DIRECTORIES: /opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current/gcc/aarch64-apple-darwin21/12;/opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current/gcc;/opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib
-- CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES Before Fix: gfortran;emutls_w;gcc;quadmath;emutls_w;gcc;gcc
-- LIBGCC_S_PATH = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/libgcc_s.1.tbd.
-- LIBGCC_S = gcc_s.1.tbd.
-- CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES: gfortran;emutls_w;gcc;quadmath;emutls_w;gcc;gcc;gcc_s.1.tbd
-- LIBS: /opt/homebrew/lib/libhdf5.dylib;/usr/lib/libpython2.7.dylib
-- decay.cpp exists, no need to download or extract!
-- decay-apple-clang.s exists, no need to download or extract!
-- cram.c exists, no need to download or extract!
-- cram-apple-clang.s exists, no need to download or extract!
-- Not fast compiling decay.cpp since PyNE fast compile is disabled.
-- Not fast compiling cram.c since PyNE fast compile is disabled.
-- Include paths for /Users/cwg1231/Downloads/pyne-0.7.7/src: /opt/homebrew/include;/Users/cwg1231/opt/anaconda3/lib/python3.9/site-packages/numpy/core/include;/Users/cwg1231/Downloads/pyne-0.7.7/build/pyne;/Users/cwg1231/Downloads/pyne-0.7.7/src
-- Include paths for /Users/cwg1231/Downloads/pyne-0.7.7/pyne: /opt/homebrew/include;/Users/cwg1231/opt/anaconda3/lib/python3.9/site-packages/numpy/core/include;/Users/cwg1231/Downloads/pyne-0.7.7/build/pyne;/Users/cwg1231/Downloads/pyne-0.7.7/src
-- Modules to Cythonize: ace;bins;data;dtypes;endf;enrichment;extra_types;jsoncpp;material;material_library;nucname;particle;pyne_config;rxname;source;stlcontainers;tally;transmuters;_utils
-- F2PY F90 FLAGS: 
-- Include paths for /Users/cwg1231/Downloads/pyne-0.7.7/pyne/xs: /opt/homebrew/include;/Users/cwg1231/opt/anaconda3/lib/python3.9/site-packages/numpy/core/include;/Users/cwg1231/Downloads/pyne-0.7.7/build/pyne;/Users/cwg1231/Downloads/pyne-0.7.7/src
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/cwg1231/Downloads/pyne-0.7.7/build
[  0%] Built target ReplicatePythonSourceTree
Scanning dependencies of target pyne
Consolidate compiler generated dependencies of target pyne
[  1%] Building CXX object src/CMakeFiles/pyne.dir/utils.cpp.o
[  2%] Linking CXX shared library libpyne.dylib
[ 24%] Built target pyne
Consolidate compiler generated dependencies of target ace
[ 25%] Linking CXX shared module ace.so
[ 27%] Built target ace
Consolidate compiler generated dependencies of target bins
[ 28%] Linking CXX shared module bins.so
[ 31%] Built target bins
Scanning dependencies of target data
Consolidate compiler generated dependencies of target data
[ 32%] Linking CXX shared module data.so
[ 34%] Built target data
Scanning dependencies of target dtypes
Consolidate compiler generated dependencies of target dtypes
[ 36%] Linking CXX shared module dtypes.so
[ 38%] Built target dtypes
Consolidate compiler generated dependencies of target endf
[ 39%] Linking CXX shared module endf.so
[ 42%] Built target endf
Scanning dependencies of target enrichment
Consolidate compiler generated dependencies of target enrichment
[ 43%] Linking CXX shared module enrichment.so
[ 45%] Built target enrichment
Scanning dependencies of target extra_types
Consolidate compiler generated dependencies of target extra_types
[ 46%] Linking CXX shared module extra_types.so
[ 49%] Built target extra_types
Scanning dependencies of target jsoncpp
Consolidate compiler generated dependencies of target jsoncpp
[ 50%] Linking CXX shared module jsoncpp.so
[ 53%] Built target jsoncpp
Scanning dependencies of target material
Consolidate compiler generated dependencies of target material
[ 54%] Linking CXX shared module material.so
[ 56%] Built target material
Scanning dependencies of target material_library
Consolidate compiler generated dependencies of target material_library
[ 57%] Linking CXX shared module material_library.so
[ 60%] Built target material_library
Scanning dependencies of target nucname
Consolidate compiler generated dependencies of target nucname
[ 61%] Linking CXX shared module nucname.so
[ 63%] Built target nucname
Scanning dependencies of target particle
Consolidate compiler generated dependencies of target particle
[ 65%] Linking CXX shared module particle.so
[ 67%] Built target particle
Scanning dependencies of target pyne_config
Consolidate compiler generated dependencies of target pyne_config
[ 68%] Linking CXX shared module pyne_config.so
[ 71%] Built target pyne_config
Scanning dependencies of target rxname
Consolidate compiler generated dependencies of target rxname
[ 72%] Linking CXX shared module rxname.so
[ 74%] Built target rxname
Scanning dependencies of target source
Consolidate compiler generated dependencies of target source
[ 75%] Linking CXX shared module source.so
[ 78%] Built target source
Scanning dependencies of target stlcontainers
Consolidate compiler generated dependencies of target stlcontainers
[ 79%] Linking CXX shared module stlcontainers.so
[ 81%] Built target stlcontainers
Consolidate compiler generated dependencies of target tally
[ 83%] Linking CXX shared module tally.so
[ 85%] Built target tally
Scanning dependencies of target transmuters
Consolidate compiler generated dependencies of target transmuters
[ 86%] Linking CXX shared module transmuters.so
[ 89%] Built target transmuters
Consolidate compiler generated dependencies of target _utils
[ 90%] Linking CXX shared module _utils.so
[ 92%] Built target _utils
Scanning dependencies of target cram
Consolidate compiler generated dependencies of target cram
[ 93%] Linking C shared module cram.so
[ 96%] Built target cram
Consolidate compiler generated dependencies of target models
[ 97%] Linking CXX shared module models.so
[100%] Built target models
[  0%] Built target ReplicatePythonSourceTree
Consolidate compiler generated dependencies of target pyne
[ 24%] Built target pyne
[ 27%] Built target ace
[ 31%] Built target bins
[ 34%] Built target data
[ 38%] Built target dtypes
[ 42%] Built target endf
[ 45%] Built target enrichment
[ 49%] Built target extra_types
[ 53%] Built target jsoncpp
[ 56%] Built target material
[ 60%] Built target material_library
[ 63%] Built target nucname
[ 67%] Built target particle
[ 71%] Built target pyne_config
[ 74%] Built target rxname
[ 78%] Built target source
[ 81%] Built target stlcontainers
[ 85%] Built target tally
[ 89%] Built target transmuters
[ 92%] Built target _utils
[ 96%] Built target cram
[100%] Built target models
Install the project...
-- Install configuration: "Release"
############### Begin Python Install ###############
-- Python installer:
  PYTHON_EXECUTABLE: /Users/cwg1231/opt/anaconda3/bin/python3
  CMAKE_INSTALL_PREFIX: /Users/cwg1231/opt/anaconda3
  CMAKE_CURRENT_BINARY_DIR: /Users/cwg1231/Downloads/pyne-0.7.7/build
/Users/cwg1231/Downloads/pyne-0.7.7/build/setup_sub.py:9: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/Users/cwg1231/Downloads/pyne-0.7.7/build/pyne/__init__.py:22: Warning: Error importing PyNE: you should not try to import PyNE from its source directory; please exit the PyNE source tree, and relaunch your python interpreter from there.
  warn(msg, Warning)
Traceback (most recent call last):
  File "/Users/cwg1231/Downloads/pyne-0.7.7/build/setup_sub.py", line 26, in <module>
    from pyne.pyne_version import PYNE_VERSION
  File "/Users/cwg1231/Downloads/pyne-0.7.7/build/pyne/__init__.py", line 14, in <module>
    from .pyne_config import *
ImportError: dlopen(/Users/cwg1231/Downloads/pyne-0.7.7/build/pyne/pyne_config.so, 0x0002): tried: '/Users/cwg1231/Downloads/pyne-0.7.7/build/pyne/pyne_config.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/pyne_config.so' (no such file), '/usr/lib/pyne_config.so' (no such file)
CMake Error at cmake/SetupSubPyInstall.cmake:15 (message):
  Process setup_sub.py install failed, res_var = '1'
Call Stack (most recent call first):
  cmake_install.cmake:41 (include)


make: *** [install] Error 1

--------------------

If you are having issues building pyne, please report your problem to pyne-dev@googlegroups.com or look for help at http://pyne.io

--------------------
Traceback (most recent call last):
  File "/Users/cwg1231/Downloads/pyne-0.7.7/setup.py", line 481, in <module>
    main()
  File "/Users/cwg1231/Downloads/pyne-0.7.7/setup.py", line 464, in main
    main_safe(ns)
  File "/Users/cwg1231/Downloads/pyne-0.7.7/setup.py", line 456, in main_safe
    main_body(ns)
  File "/Users/cwg1231/Downloads/pyne-0.7.7/setup.py", line 440, in main_body
    rtn = subprocess.check_call(["make", "install"], cwd=ns.build_dir)
  File "/Users/cwg1231/opt/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'install']' returned non-zero exit status 2.
(base) cwg1231@Connors-MacBook-Air-3 pyne-0.7.7 % python3
Python 3.9.13 (main, Aug 25 2022, 18:29:29) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.

```
</details>
**Please complete the following information regarding your system:**<br/>

 - Hardware: M1 Macbook Air 2020 
 - OS: MacOS Monterey 12.2.1
 - PyNE Version: 0.7.7 </br>
 - HDF5 library version: 1.12.2 </br>
 - NUMPY_VERSION_STRING = 1.21.5
 - Python version: 3.9.13
 - Clang 12.0.0

**Additional Context**<br/>

**Comment by sudo-nano** [comment]
Turns out that I had forgotten to clean before changing compiler options and recompiling, so not all of the compiled executables were the correct architecture.

**Comment by gonuke** [comment]
I'm glad you were able to work this out.  I did expect the `--slow` option to work, so that's promising.  It does slow things down and take a lot of RAM, so it would be good to some day store the Apple silicon version of these files to accelerate things.
