### ISSUE TITLE
Programe cc1 killed when compiling cram

### ISSUE THREAD

**Issue by HowYoungLan** [pyne/pyne#1465]
setup.py:38: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
atomic_data.h generated is the same as existing file, skipping.
atomic_data.cpp generated is the same as existing file, skipping.
/usr/bin/cmake
CMake command is
cmake .. -DCMAKE_INSTALL_PREFIX=/home/hylan/.local -DWITH_MOAB=ON -DMOAB_ROOT=/home/hylan/SoftWares/dagmc_bld/MOAB -DWITH_DAGMC=ON -DDAGMC_ROOT=/home/hylan/SoftWares/dagmc_bld/DAGMC -DENABLE_SPATIAL_SOLVERS=ON -DPYTHON_EXECUTABLE=/usr/bin/python3

                                  /   \       
                          )      ((   ))     (                          
(@)                      /|\      ))_((     /|\                          
|-|                     / | \    (/\|/\)   / | \                      (@) 
| | -------------------/--|-voV---\`|'/--Vov-|--\---------------------|-|
|-|                         '^`   (o o)  '^`                          | |
| |                               `\Y/'                               |-|
|-|                                                                   | |
| |        /\             ___           __  __             /\         |-|
|-|       /^~\           / _ \_   _  /\ \ \/__\           /^~\        | |  
| |       /^~\          / /_)/ | | |/  \/ /_\             /^~\        |-|
|-|       /^~\         / ___/| |_| / /\  //__             /^~\        | | 
| |       ^||`         \/     \__, \_\ \/\__/             ^||`        |-|  
|-|        ||                |____/                        ||         | | 
| |       ====                                            ====        |-|
|-|                                                                   | |
| |                                                                   |-|
|-|___________________________________________________________________| |
(@)              l   /\ /         ( (       \ /\   l                `\|-|
                 l /   V           \ \       V   \ l                  (@)
                 l/                _) )_          \I                   
                                   `\ /'
                                     `  

-- Pyne platform defined as: __LINUX__
-- Checking whether to build spatial solvers
-- -- Checking CMAKE_CXX_COMPILER_ID: GNU
-- -- -- Checking CMAKE_CXX_COMPILER_VERSION: 10.3.0
-- -- -- Checking if APPLE: 
-- Build spatial solvers: true
-- Build type: Release
-- PyNE Fast Compile: TRUE
-- CMAKE_INSTALL_RPATH: /home/hylan/.local/lib:/usr/lib
-- CMake Install Prefix: /home/hylan/.local
-- Dependency Root Dir (DEPS_ROOT_DIR): /usr
-- Dependency Hints (DEPS_HINTS): HINTS;/usr
-- Dependency Binary Hints (DEPS_BIN_HINTS): HINTS;/usr;/usr/bin
-- Dependency Library Hints (DEPS_LIB_HINTS): HINTS;/usr;/usr/lib
-- Dependency Include Hints (DEPS_INCLUDE_HINTS): HINTS;/usr/include
-- HDF5 Root: /home/hylan/dagmc_bld/HDF5
In file included from /home/hylan/dagmc_bld/HDF5/include/H5public.h:37,
                 from /home/hylan/dagmc_bld/HDF5/include/hdf5.h:24,
                 from /home/hylan/SoftWares/dagmc_bld/pyne/pyne/build/CMakeFiles/hdf5/cmake_hdf5_test.c:1:
/usr/include/features.h:187:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
  187 | # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
      |   ^~~~~~~
--    HDF5 Include directory: /home/hylan/dagmc_bld/HDF5/include
--    HDF5 Library directories: /home/hylan/dagmc_bld/HDF5/lib
--    HDF5 Libraries: /home/hylan/dagmc_bld/HDF5/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so
--    HDF5 library version: 1.8.13
-- MOAB Root: /home/hylan/SoftWares/dagmc_bld/MOAB
-- Could NOT find MOAB (missing: MOAB_INCLUDE_DIRS) 
-- MOAB Found: FALSE
-- DAGMC: Not searching because MOAB was not found.
-- PYTHON_EXECUTABLE: /usr/bin/python3
-- PYTHON_SITE_PACKAGES: /home/hylan/.local/local/lib/python3.8/dist-packages
-- NUMPY_VERSION_STRING = 1.23.5
-- CMAKE_Fortran_IMPLICIT_LINK_DIRECTORIES: /usr/lib/gcc/x86_64-linux-gnu/9;/usr/lib/x86_64-linux-gnu;/usr/lib;/lib/x86_64-linux-gnu;/lib
-- CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES: gfortran;m;gcc_s;gcc;quadmath;m;gcc_s;gcc;c;gcc_s;gcc
-- NUMPY_VERSION_STRING = 1.23.5
-- F2PY Executable: /usr/local/bin/f2py
-- F2PY Version: 1.23.5
-- A library with LAPACK API found.
-- Found LAPACK Linker Flags: 
-- Found LAPACK Libraries: /usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libblas.so
-- Found BLAS Libraries: /usr/lib/x86_64-linux-gnu/libblas.so
-- LIBS: /home/hylan/dagmc_bld/HDF5/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libpython3.8.so
-- decay.cpp exists, no need to download or extract!
-- decay-linux-gnu.s exists, no need to download or extract!
-- cram.c exists, no need to download or extract!
-- Extracting cram-linux-gnu.tar.gz
-- Compiling decay.cpp fast from assembly decay-linux-gnu.s
-- Not fast compiling cram.c since /home/hylan/SoftWares/dagmc_bld/pyne/pyne/src/cram-linux-gnu.s does not exist.
-- Include paths for /home/hylan/SoftWares/dagmc_bld/pyne/pyne/src: /home/hylan/dagmc_bld/HDF5/include;/home/hylan/.local/lib/python3.8/site-packages/numpy/core/include;/home/hylan/SoftWares/dagmc_bld/pyne/pyne/build/pyne;/home/hylan/SoftWares/dagmc_bld/pyne/pyne/src
-- Include paths for /home/hylan/SoftWares/dagmc_bld/pyne/pyne/pyne: /home/hylan/dagmc_bld/HDF5/include;/home/hylan/.local/lib/python3.8/site-packages/numpy/core/include;/home/hylan/SoftWares/dagmc_bld/pyne/pyne/build/pyne;/home/hylan/SoftWares/dagmc_bld/pyne/pyne/src
-- Modules to Cythonize: ace;bins;data;dtypes;endf;enrichment;extra_types;jsoncpp;material;material_library;nucname;particle;pyne_config;rxname;source;stlcontainers;tally;transmuters;_utils
-- F2PY F90 FLAGS: 
-- Include paths for /home/hylan/SoftWares/dagmc_bld/pyne/pyne/pyne/xs: /home/hylan/dagmc_bld/HDF5/include;/home/hylan/.local/lib/python3.8/site-packages/numpy/core/include;/home/hylan/SoftWares/dagmc_bld/pyne/pyne/build/pyne;/home/hylan/SoftWares/dagmc_bld/pyne/pyne/src
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hylan/SoftWares/dagmc_bld/pyne/pyne/build
[  0%] Built target ReplicatePythonSourceTree
Scanning dependencies of target pyne
[  1%] Building C object src/CMakeFiles/pyne.dir/cram.c.o
In file included from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                 from /usr/include/string.h:26,
                 from /home/hylan/SoftWares/dagmc_bld/pyne/pyne/src/cram.c:3:
/usr/include/features.h:187:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
  187 | # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
      |   ^~~~~~~
cc: fatal error: Killed signal terminated program cc1
compilation terminated.
make[2]: *** [src/CMakeFiles/pyne.dir/build.make:82: src/CMakeFiles/pyne.dir/cram.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:224: src/CMakeFiles/pyne.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

--------------------

If you are having issues building pyne, please report your problem to pyne-dev@googlegroups.com or look for help at http://pyne.io

--------------------
Traceback (most recent call last):
  File "setup.py", line 481, in <module>
    main()
  File "setup.py", line 464, in main
    main_safe(ns)
  File "setup.py", line 456, in main_safe
    main_body(ns)
  File "setup.py", line 438, in main_body
    rtn = subprocess.check_call(["make"] + ns.make_args, cwd=ns.build_dir)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.

**Comment by HowYoungLan** [comment]
I'm installing PyNE in Ubuntu 21.04. The PyNE version is the most stable one.

**Comment by gonuke** [comment]
To compile the cram capability from source requires a very large amount of system memory.  If not enough memory is available, the compiler will die.  Because of this, we provide precompiled assembly code to be downloaded to avoid this.  It looks like your system did not access this for some reason:

```
-- cram.c exists, no need to download or extract!
-- Extracting cram-linux-gnu.tar.gz
-- Compiling decay.cpp fast from assembly decay-linux-gnu.s
-- Not fast compiling cram.c since /home/hylan/SoftWares/dagmc_bld/pyne/pyne/src/cram-linux-gnu.s does not exist.
```

I'm not sure why....
