### ISSUE TITLE
pyne install with conda

### ISSUE THREAD

**Issue by Knights-Templars** [pyne/pyne#1483]
**Describe the Bug**<br/>

**To Reproduce**<br/>
Specify the necessary steps to reproduce the behavior. For example,
supply the setup.py command used for building if there is a build error,
or the steps taken when using the PyNE that produced the error.

**Expected Behavior**<br/>

**Screenshots or Code Snippets**<br/>
If applicable, add screenshots or snippets of code and error messages to help explain your problem.
Note, please do not include screenshots or snippets of code that is export controlled.

**Please complete the following information regarding your system:**<br/>
 - OS: [e.g. ubuntu Linux]
 - PyNE Version: [e.g. 0.7.1]
 - Versions of dependencies installed with: [e.g. HDF5 1.10]

**Additional Context**<br/>

I am trying to install pyne with conda on my macos M1. I have created a .yml as mentioned here https://github.com/pyne/pyne/issues/1452, but still getting the same error as given in the attachment. Can someone please help. 

This is the error I am getting. 

conda env update --file pyne.yml
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1118, in __call__
        return func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/notices/core.py", line 109, in wrapper
        return func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_update.py", line 132, in execute
        result[installer_type] = installer.install(prefix, specs, args, env)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda_env/installers/conda.py", line 49, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 136, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 179, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 284, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 451, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 1061, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/index.py", line 275, in get_reduced_index
        push_record(record)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/index.py", line 249, in push_record
        combined_depends = record.combined_depends
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/models/records.py", line 338, in combined_depends
        result = {ms.name: ms for ms in MatchSpec.merge(self.depends)}
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 481, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 481, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 512, in _merge
        final = this_component.merge(that_component)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 787, in merge
        raise ValueError("Incompatible component merge:\n  - %r\n  - %r"
    ValueError: Incompatible component merge:
      - 'mpi_openmpi_*'
      - 'mpi_openmpi_tempest*'

`$ /opt/miniconda3/bin/conda-env update --file pyne.yml --prune`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=nuclear
                CONDA_EXE=/opt/miniconda3/bin/conda
             CONDA_PREFIX=/opt/miniconda3/envs/nuclear
           CONDA_PREFIX_1=/opt/miniconda3
           CONDA_PREFIX_2=/opt/miniconda3/envs/tardis-nuclear
           CONDA_PREFIX_3=/opt/miniconda3
    CONDA_PROMPT_MODIFIER=(nuclear)
         CONDA_PYTHON_EXE=/opt/miniconda3/bin/python
               CONDA_ROOT=/opt/miniconda3
              CONDA_SHLVL=4
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
               LD_PRELOAD=<not set>
                  MANPATH=/opt/homebrew/share/man::
                     PATH=/opt/miniconda3/envs/nuclear/bin:/opt/miniconda3/condabin:/opt/homebre
                          w/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:
                          /usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/var
                          /run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:
                          /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/v
                          ar/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleint
                          ernal/bin:/Users/anirbandutta/.iraf/bin:/Users/anirbandutta/.iraf/bin:
                          /Users/anirbandutta/.iraf/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : nuclear
    active env location : /opt/miniconda3/envs/nuclear
            shell level : 4
       user config file : /Users/anirbandutta/.condarc
 populated config files : /Users/anirbandutta/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=10.16=0
                          __unix=0=0
       base environment : /opt/miniconda3  (writable)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : http://ssb.stsci.edu/astroconda/osx-64
                          http://ssb.stsci.edu/astroconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /Users/anirbandutta/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /Users/anirbandutta/.conda/envs
               platform : osx-64
             user-agent : conda/22.11.1 requests/2.26.0 CPython/3.9.5 Darwin/22.5.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: N

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

**Comment by gonuke** [comment]
I know we have not explicitly added support for Apple silicon to our conda-forge images, so that may be part of the issue.  We'll have to investigate on the next release/re-spin of our conda feedstock.

**Comment by Knights-Templars** [comment]
Thanks.

**Comment by ahnaf-tahmid-chowdhury** [comment]
It seems the issue is related to a mismatch in the MPI version. I’m wondering if PyNE comes with MPI functionality. Was this run in a fresh environment where no MPI related packages were previously installed or in the PATH?
