### ISSUE TITLE
32 bit test failures

### ISSUE THREAD

**Issue by py1sl** [pyne/pyne#315]
When compiling on an 32 bit ubuntu VM 
 3 tests fail and 3 tests error, believed to be 32 bit issues
## ERROR: test_stlcontainers.test_map_uint_str

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/slilley/pyne/tests/test_stlcontainers.py", line 297, in test_map_uint_str
    assert_equal(m[4294967295], 'Take')
  File "stlcontainers.pyx", line 945, in pyne.stlcontainers._MapUIntStr.__getitem__ (/home/slilley/pyne/build/pyne/stlcontainers.cxx:14655)
TypeError: Only unsigned integer keys are valid.
-------------------- >> begin captured stdout << ---------------------
{1: u'On', 65: u'Me'}

--------------------- >> end captured stdout << ----------------------
# 
## ERROR: test_stlcontainers.test_map_uint_uint

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/slilley/pyne/tests/test_stlcontainers.py", line 407, in test_map_uint_uint
    assert_almost_equal(m[4294967295], 65)
  File "stlcontainers.pyx", line 1229, in pyne.stlcontainers._MapUIntUInt.__getitem__ (/home/slilley/pyne/build/pyne/stlcontainers.cxx:18520)
TypeError: Only unsigned integer keys are valid.
-------------------- >> begin captured stdout << ---------------------
{1: 42, 65: 4294967295L}

--------------------- >> end captured stdout << ----------------------
# 
## ERROR: test_stlcontainers.test_map_uint_double

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/slilley/pyne/tests/test_stlcontainers.py", line 627, in test_map_uint_double
    assert_almost_equal(m[4294967295], 42.42)
  File "stlcontainers.pyx", line 1797, in pyne.stlcontainers._MapUIntDouble.__getitem__ (/home/slilley/pyne/build/pyne/stlcontainers.cxx:25787)
TypeError: Only unsigned integer keys are valid.
-------------------- >> begin captured stdout << ---------------------
{1: 18.0, 65: -65.5555}

--------------------- >> end captured stdout << ----------------------
# 
## FAIL: test_data.test_b

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(_self.arg)
  File "/home/slilley/pyne/tests/test_data.py", line 40, in test_b
    assert_equal(data.b('SM149'), math.sqrt(abs(bc)__2 + abs(bi)_*2))
AssertionError: 3.996973855306036e-12 != 3.996973855306037e-12
# 
## FAIL: test_endf.test_get

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/slilley/pyne/tests/test_endf.py", line 412, in test_get
    assert_array_equal(exp, obs)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 707, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 636, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 8.33333333333%)
 x: array([  4.89842100e+03,   6.76812300e+00,   0.00000000e+00,
         1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         2.12312400e+06,   8.12314200e-06,   2.12321200e+06,
         8.23123100e-06,  -2.23121100e+06,   8.12342100e-06])
 y: array([  4.89842100e+03,   6.76812300e+00,   0.00000000e+00,
         1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         2.12312400e+06,   8.12314200e-06,   2.12321200e+06,
         8.23123100e-06,  -2.23121100e+06,   8.12342100e-06])
# 
## FAIL: test_endf.test_discretize

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/slilley/pyne/tests/test_endf.py", line 965, in test_discretize
    assert_equal(nonelastic_c, exp)
AssertionError: Lists differ: [0.54334609294912528, 0.212062... != [0.5433460929491253, 0.2120625...

First differing element 4:
0.0561939600283
0.0561939600283

Diff is 2280 characters long. Set self.maxDiff to None to see it.

---

Ran 629 tests in 143.158s

FAILED (SKIP=15, errors=3, failures=3)

**Comment by gonuke** [comment]
Closing as "won't fix" because 32-bit is even more rare than 6 years ago.
