### ISSUE TITLE
Add `jinja2` to requirements

### ISSUE THREAD

**Issue by crbates** [pyne/pyne#689]
`decaygen.py` which is imported in `test_decay.py` requires jinja2.

**Comment by scopatz** [comment]
Correct me if I am wrong, but I think jinja2 is a sphinx dependency.

**Comment by crbates** [comment]
yes but sphinx is an indirect docs dependency not a tests fail if you don't have this dependency.

**Comment by scopatz** [comment]
True.

**Comment by crbates** [comment]
but now the latter happens if you try to run nosetests without jinja2 : 
```
======================================================================
ERROR: Failure: ImportError (No module named jinja2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/venv/pyne/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/venv/pyne/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/venv/pyne/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/pyne/tests/test_decay.py", line 33, in <module>
    import decaygen
  File "/Users/pyne/src/decaygen.py", line 12, in <module>
    import jinja2
ImportError: No module named jinja2
```

**Comment by scopatz** [comment]
Oh! I totally forgot about that with the decay tests.
