### ISSUE TITLE
pyne hdf5 problem with anaconda

### ISSUE THREAD

**Issue by wkerzendorf** [pyne/pyne#737]
Hi when installing pyne through anaconda (`conda install -c cyclus -c pyne pyne=0.5.0`). I get this error when import pyne:

```
Users/wkerzend/anaconda3/envs/nuclear-test2/lib/python2.7/site-packages/pyne/__init__.py:15: Warning: Error importing PyNE: you should not try to import PyNE from its source directory; please exit the PyNE source tree, and relaunch your python interpreter from there.
  warn(msg, Warning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wkerzend/anaconda3/envs/nuclear-test2/lib/python2.7/site-packages/pyne/__init__.py", line 10, in <module>
    from .pyne_config import *
ImportError: dlopen(/Users/wkerzend/anaconda3/envs/nuclear-test2/lib/python2.7/site-packages/pyne/pyne_config.so, 2): Library not loaded: @rpath/libhdf5.9.dylib
  Referenced from: /Users/wkerzend/anaconda3/envs/nuclear-test2/lib/python2.7/site-packages/pyne/pyne_config.so
  Reason: image not found
```

This can be alleviated by downgrading hdf5 with `conda install hdf5=1.8.14`

**Comment by skc222** [comment]
Newer version of conda target won't have this issue. So, I think this issue can be safely closed. (any dissent?) 
Merged PR for changing conda instructions- https://github.com/pyne/pyne.github.com/pull/3
