### ISSUE TITLE
strange CI failure in PR

### ISSUE THREAD

**Issue by rwcarlsen** [pyne/pyne#778]
Observed in #777 for only the python 2 CI job and had nothing to do with the PR:

```
Testing test_ace.py:
E
======================================================================
ERROR: Failure: ValueError (numpy.dtype has the wrong size, try recompiling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/miniconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/miniconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/pyne/pyne/tests/test_ace.py", line 7, in <module>
    import pyne.ace
  File "__init__.pxd", line 155, in init pyne.ace (/home/travis/miniconda/conda-bld/work/build/pyne/ace.cxx:31469)
ValueError: numpy.dtype has the wrong size, try recompiling
----------------------------------------------------------------------
Ran 1 test in 0.001s
FAILED (errors=1)
Testing failed on test_ace.py
The command "./travis-run-tests.sh" exited with 1.
```

**Comment by scopatz** [comment]
This has now been fixed. It was an issue with the pytaps package
