### ISSUE TITLE
Ipython not actually needed for setup

### ISSUE THREAD

**Issue by makeclean** [pyne/pyne#810]
Right now we have an unofficial dependency which is IPython, not listed at www.pyne.io. My guess is is that its actually needed for tests or building documentation? We should therefore move the check in https://github.com/pyne/pyne/blob/develop/setup.py#L153 to a more appropriate place?

**Comment by skc222** [comment]
@makeclean @katyhuff   I tested all sample tests without installing IPython. Does this mean that this issue is no longer open? or can you tell me why IPython is an unofficial dependency then?

**Comment by makeclean** [comment]
Guess so, its possible something change between then and now?

**Comment by skc222** [comment]
Ohh yes. You are correct. We don't need ipython for unit testing but we need to install it for example testing. Many other packages are also required for example testing. I installed all but still got following error:
```
FAILURE: ace.ipynb:
CAT: ipython nbconvert --to=python --stdout ace.ipynb
----------
Traceback (most recent call last):
  File "../execer.py", line 65, in main
    execer(f)
  File "../execer.py", line 39, in execipynb
    exec(compile(src, filename, "exec"), glb, loc)
  File "ace.ipynb", line 30, in <module>
    "    urlretrieve(\"https://www-nds.iaea.org/wolfram/w180/beta3/W180.ace\", \"W180.ace\")"
  File "pyne/ace.pyx", line 181, in pyne.ace.Library.read (/home/ubuntu/Downloads/pyne-0.5.3/build/pyne/ace.cxx:5440)
  File "pyne/ace.pyx", line 288, in pyne.ace.Library._read_ascii (/home/ubuntu/Downloads/pyne-0.5.3/build/pyne/ace.cxx:7416)
ValueError: could not convert string to float: html>

FAILURE: discretized_teapot.ipynb:
CAT: ipython nbconvert --to=python --stdout discretized_teapot.ipynb
----------
Traceback (most recent call last):
  File "../execer.py", line 65, in main
    execer(f)
  File "../execer.py", line 39, in execipynb
    exec(compile(src, filename, "exec"), glb, loc)
  File "discretized_teapot.ipynb", line 11, in <module>
    {
ImportError: No module named dagmc

FAILURE: endf_reader.ipynb:
CAT: ipython nbconvert --to=python --stdout endf_reader.ipynb
----------
Traceback (most recent call last):
  File "../execer.py", line 65, in main
    execer(f)
  File "../execer.py", line 39, in execipynb
    exec(compile(src, filename, "exec"), glb, loc)
  File "endf_reader.ipynb", line 165, in <module>
    "The `pyne.endf.Evaluation` class provides a facility for parsing data in an ENDF file. Parsing of all data other than covariances (MF=30+) is supported has been tested against the ENDF/B-VII.1 neutron, photoatomic, electroatomic, atomic relaxation, and photonuclear sublibraries. In this example, we will use the `Evaluation` class to look at typical data in the ENDF/B-VII.1 evaluation of U-235."
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 3455, in semilogx
    ret = ax.semilogx(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 1599, in semilogx
    self.set_xscale('log', **d)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/projections/polar.py", line 583, in set_xscale
    raise NotImplementedError("You can not set the xscale on a polar plot.")
NotImplementedError: You can not set the xscale on a polar plot.

FAILURE: mesh_tags.ipynb:
CAT: ipython nbconvert --to=python --stdout mesh_tags.ipynb
----------
Traceback (most recent call last):
  File "../execer.py", line 65, in main
    execer(f)
  File "../execer.py", line 39, in execipynb
    exec(compile(src, filename, "exec"), glb, loc)
  File "mesh_tags.ipynb", line 96, in <module>
    {
NameError: name 'PyneMoabHex8StaticOutput' is not defined

FAILURE: origen22_h1_xs.ipynb:
CAT: ipython nbconvert --to=python --stdout origen22_h1_xs.ipynb
----------
Traceback (most recent call last):
  File "../execer.py", line 65, in main
    execer(f)
  File "../execer.py", line 39, in execipynb
    exec(compile(src, filename, "exec"), glb, loc)
  File "origen22_h1_xs.ipynb", line 37, in <module>
    "water.from_atom_frac({'H1': 2.0, 'O16': 1.0})\n",
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyne-0.5.3-py2.7.egg/pyne/origen22.py", line 1120, in parse_tape9
    tape9 = open(tape9, 'r')
IOError: [Errno 2] No such file or directory: 'BASE_TAPE9.INP'

------
TOTAL: 15 -  10 successes 5 failures
Closing remaining open files:/home/ubuntu/.local/lib/python2.7/site-packages/pyne-0.5.3-py2.7.egg/pyne/nuc_data.h5...done/home/ubuntu/.local/lib/python2.7/site-packages/pyne-0.5.3-py2.7.egg/pyne/nuc_data.h5...done
ubuntu@ubuntu:~/Downloads/pyne-0.5.3/examples$ 

```
Same with tutorial testing:
```
FAILURE: 05-cross-sections.ipynb:
CAT: ipython nbconvert --to=python --stdout 05-cross-sections.ipynb
----------
Traceback (most recent call last):
  File "../execer.py", line 65, in main
    execer(f)
  File "../execer.py", line 39, in execipynb
    exec(compile(src, filename, "exec"), glb, loc)
  File "05-cross-sections.ipynb", line 138, in <module>
    "         9.13386000e-02,   9.53971000e-02,   9.82263000e-02,\n",
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyne-0.5.3-py2.7.egg/pyne/xs/cache.py", line 68, in __init__
    ds = ds(dst_group_struct=group_struct)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyne-0.5.3-py2.7.egg/pyne/xs/data_source.py", line 600, in __init__
    super(EAFDataSource, self).__init__(**kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyne-0.5.3-py2.7.egg/pyne/xs/data_source.py", line 122, in __init__
    self.dst_group_struct = dst_group_struct
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyne-0.5.3-py2.7.egg/pyne/xs/data_source.py", line 151, in dst_group_struct
    elif same_arr_or_none(dst_group_struct, self._dst_group_struct):
AttributeError: 'EAFDataSource' object has no attribute '_dst_group_struct'

FAILURE: 11-ensdf-processing.ipynb:
CAT: ipython nbconvert --to=python --stdout 11-ensdf-processing.ipynb
----------
Traceback (most recent call last):
  File "../execer.py", line 65, in main
    execer(f)
  File "../execer.py", line 39, in execipynb
    exec(compile(src, filename, "exec"), glb, loc)
  File "11-ensdf-processing.ipynb", line 37, in <module>
    "language": "python",
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyne-0.5.3-py2.7.egg/pyne/ensdf_processing.py", line 120, in alphad
    stdin=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

------
TOTAL: 12 -  10 successes 2 failures
Closing remaining open files:/home/ubuntu/.local/lib/python2.7/site-packages/pyne-0.5.3-py2.7.egg/pyne/nuc_data.h5...done
ubuntu@ubuntu:~/Downloads/pyne-0.5.3/tutorial$ 
```
Any views on these errors?

**Comment by opotowsky** [comment]
@gonuke or @bam241 :

First, the main question directly related to this issue, is whether jupyter notebooks are a dependency. Right now it is listed as a dependency to build _documentation only_ on the [readme](https://github.com/pyne/pyne/blob/develop/readme.rst) but that info is not on the [site](http://pyne.io/install/linux_source.html#linux-source). Additionally `jupyter` isn't in any of the install scripts I spot-checked. Since it is required for testing the examples, should it be bumped up to optional? Or if other dependencies that don't fit into a neat box have been ID-ed, we can make a new section. 

This issue in the discussion also brings up some failures I can't diagnose as well as python 2 vs 3 failures. Some of the notebooks have python 2 syntax, and so I get a lot of failures from that since I'm using python 3. I'm not up-to-date on the python 2 vs 3 debacle as it relates to pyne, so I'm not sure how to proceed.
