### ISSUE TITLE
ZZZAAA Ca (element and isotopes) mistaken for He

### ISSUE THREAD

**Issue by ghost** [pyne/pyne#846]
When specifying a material composition, if one uses the ZZZAAA ID naming scheme but dropping the leading zero, i.e. 20000 for elemental Ca, you get elemental He (2000) in your material. Similarly, Ca-40 gives He-4, as if pyne has dropped the trailing zero. Specifying the zaids as strings doesn't have any effect.

```
>>> print(Material({20040:1}))
Material:
mass = 1.0
density = -1.0
atoms per molecule = -1.0
-------------------------
He4    1.0
```

If I try 020000 I get:

```
>>> print(Material({020000:1}))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyne/material.pyx", line 1538, in pyne.material.Material.__str__ (/Users/Fred/pyne-0.5.0/build/pyne/material.cxx:17006)
  File "pyne/nucname.pyx", line 220, in pyne.nucname.name (/Users/Fred/pyne-0.5.0/build/pyne/nucname.cxx:3478)
RuntimeError: Indeterminate nuclide form: 81920000
```

Am I doing something wrong?

**Comment by ghost** [comment]
I know I can specify Ca40 or whatever, but I want to read in an MCNP definition from a file.

**Comment by scopatz** [comment]
Hi @sprogg77 - I am assuming that you are using Python 2 here?  Note that `020000` doesn't really work because _Python_ intreprets leading zeros as octal numbers (rather than decimal) and `020000 == 8192`.

Furthermore, as you noticed, `20000` is an  indeterminate form. This means that you need to use a more specific format, such as the text form or the full zzzaaammmm form, namely `20000000`.

Alternatively, if you _know_ that you have a number in MCNP format, you can use the `pyne.nucname.mcnp_to_id()` and `pyne.nucname.mcnp()` functions to convert to/from id format. See http://pyne.io/pyapi/nucname.html for more details.

Also, I thought that we had a way to load in an MCNP material as a pyne material, but I can't find it now.  Maybe @elliottbiondo knows more.

**Comment by ghost** [comment]
Ahh I see. I thought the MCNP format was the standard. I was unaware of the plethora of naming schemes. Well, it wouldn't be nuclear data without being perverse and arcane! 

Thanks for replying. I should have thought to look for documentation on naming. Is there a place for 'newbie' questions, an IRC channel or something? Or shall I keep highlighting my ignorance here?

**Comment by scopatz** [comment]
Hi @sprogg77 - we have a pyne-users@googlegroups.com mailing list. I would also be in favor of adding a gitter room for this repo too, if that is more natural.

**Comment by elliottbiondo** [comment]
@sprogg77 I am not sure this is what you are looking for but the `mats_from_inp()` function within the `pyne.mcnp` module reads in anMCNP input file and pulls out all of the materials.
