### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by lindsayad** [pyne/pyne#867]
After building pyne from source, I get a segmentation fault when trying to import pyne. Here's backtrace excerpt:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6d6aab2 in free () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff6d6aab2 in free () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff5748064 in pyne::particle::_fill_maps() ()
   from /home/lindsayad/miniconda2/envs/pyne/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/../lib/libpyne.so
#2  0x00007ffff442f8ea in _GLOBAL__sub_I_particle.cpp ()
   from /home/lindsayad/miniconda2/envs/pyne/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/../lib/libpyne.so
```

Anyone seen something like this before?

**Comment by lindsayad** [comment]
Hmm, seems like using the gcc compilers as opposed to the clang compilers fixed the issue. Interesting

**Comment by lindsayad** [comment]
Hmm, seems like using the gcc compilers as opposed to the clang compilers fixed the issue. Interesting
