### ISSUE TITLE
pyne-0.5.0 source installation error

### ISSUE THREAD

**Issue by skc222** [pyne/pyne#892]
I have downloaded pyne-0.5.0.tar.gz from https://github.com/pyne/pyne/releases/tag/0.5.0. Then I tried installing according to  http://pyne.io/install/linux_source.html#linux-source. 
<details>
 <summary>Details</summary>

```
ubuntu@ubuntu:~/Downloads/pyne-0.5.0$ python setup.py install --user
Downloading http://data.pyne.io/decay.tar.gz
/usr/bin/cmake
CMake command is
cmake .. -DHAVE_SETUPTOOLS=TRUE -DPYTHON_EXECUTABLE=/usr/bin/python
-- The Fortran compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_Fortran_IMPLICIT_LINK_DIRECTORIES = /usr/lib/gcc/x86_64-linux-gnu/5;/usr/lib/x86_64-linux-gnu;/usr/lib;/lib/x86_64-linux-gnu;/lib
-- CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES = gfortran;m;quadmath;m;c
-- Build type: Release
-- Found HDF5: debug;/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5_hl.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so;optimized;/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5_hl.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so  
-- HDF5_LIBRARY_DIRS = /usr/lib/x86_64-linux-gnu/hdf5/serial
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- PYTHON_EXECUTABLE: /usr/bin/python
-- Could NOT find MOAB (missing:  MOAB_LIBRARY MOAB_INCLUDE_DIR) 
-- MOAB Found: FALSE
-- Found Cython: /usr/bin/cython  
-- Cython Version: Cython version 0.23.4
-- Pyne platform defined as: __LINUX__
CMAKE_Fortran_COMPILER full path: /usr/bin/f95
Fortran compiler: f95
No optimized Fortran compiler flags are known, we just try -O2...

                                  /   \       
                          )      ((   ))     (                          
(@)                      /|\      ))_((     /|\                          
|-|                     / | \    (/\|/\)   / | \                      (@) 
| | -------------------/--|-voV---\`|'/--Vov-|--\---------------------|-|
|-|                         '^`   (o o)  '^`                          | |
| |                               `\Y/'                               |-|
|-|                                                                   | |
| |        /\             ___           __  __             /\         |-|
|-|       /^~\           / _ \_   _  /\ \ \/__\           /^~\        | |  
| |       /^~\          / /_)/ | | |/  \/ /_\             /^~\        |-|
|-|       /^~\         / ___/| |_| / /\  //__             /^~\        | | 
| |       ^||`         \/     \__, \_\ \/\__/             ^||`        |-|  
|-|        ||                |____/                        ||         | | 
| |       ====                                            ====        |-|
|-|                                                                   | |
| |                                                                   |-|
|-|___________________________________________________________________| |
(@)              l   /\ /         ( (       \ /\   l                `\|-|
                 l /   V           \ \       V   \ l                  (@)
                 l/                _) )_          \I                   
                                   `\ /'
                                     `  


-- CMake Install Prefix: /usr/local
-- RPATH: $ORIGIN/../lib
-- NUMPY_VERSION_STRING = 1.12.1
-- Found Numpy: 1.12.1  
-- Include paths for /home/ubuntu/Downloads/pyne-0.5.0/src: /usr/include/hdf5/serial;/usr/local/lib/python2.7/dist-packages/numpy/core/include;/home/ubuntu/Downloads/pyne-0.5.0/src
-- Include paths for /home/ubuntu/Downloads/pyne-0.5.0/pyne: /usr/include/hdf5/serial;/usr/local/lib/python2.7/dist-packages/numpy/core/include;/home/ubuntu/Downloads/pyne-0.5.0/src
CMake Warning (dev) at pyne/CMakeLists.txt:154 (target_link_libraries):
  Policy CMP0039 is not set: Utility targets may not have link dependencies.
  Run "cmake --help-policy CMP0039" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Utility target "transport_spatial_methods" should not be used as the target
  of a target_link_libraries call.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Include paths for /home/ubuntu/Downloads/pyne-0.5.0/pyne/xs: /usr/include/hdf5/serial;/usr/local/lib/python2.7/dist-packages/numpy/core/include;/home/ubuntu/Downloads/pyne-0.5.0/src;/usr/include/python2.7
-- Include paths for /home/ubuntu/Downloads/pyne-0.5.0: /usr/include/hdf5/serial;/usr/local/lib/python2.7/dist-packages/numpy/core/include
-- Copying C/C++ header files.
-- Copying Cython header files.
-- Copying scripts.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/Downloads/pyne-0.5.0/build
Scanning dependencies of target ReplicatePythonSourceTree
[  0%] Built target ReplicatePythonSourceTree
Scanning dependencies of target pyne
[  1%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/invar.f90.o
[  2%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/solvar.f90.o
[  3%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/precision_module.f90.o
[  4%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/geompack.f90.o
[  5%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/trackstruct.f90.o
[  6%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/timevar.f90.o
[  7%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/igeompack.f90.o
[  8%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/trackroutines.f90.o
[  9%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/sct_module.f90.o
[ 10%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/dgfem_kernel.f90.o
[ 11%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/ahotn_kernel_module.f90.o
/home/ubuntu/Downloads/pyne-0.5.0/src/transport_spatial_methods/3d/ahotn_kernel_module.f90:281:132:

 x*ez-36.0d0*alpha1)*dxz/ex + (ey*ez-36.0d0*beta1 )*dyz/ey ) + 3.0d0*gamma0*ez0 
                                                                             1
Error: Line truncated at (1) [-Werror=line-truncation]
/home/ubuntu/Downloads/pyne-0.5.0/src/transport_spatial_methods/3d/ahotn_kernel_module.f90:282:132:

 x*ey-36.0d0*alpha1)*dxy/ex + (ey*ez-36.0d0*gamma1)*dzy/ez ) + 3.0d0*beta0 *ey0 
                                                                             1
Error: Line truncated at (1) [-Werror=line-truncation]
/home/ubuntu/Downloads/pyne-0.5.0/src/transport_spatial_methods/3d/ahotn_kernel_module.f90:283:132:

 ex*ey-36.0d0*beta1 )*dyx/ey + (ex*ez-36.0d0*gamma1)*dzx/ez ) + 3.0d0*alpha0*ex0
                                                                              1
Error: Line truncated at (1) [-Werror=line-truncation]
f951: some warnings being treated as errors
src/CMakeFiles/pyne.dir/build.make:398: recipe for target 'src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/ahotn_kernel_module.f90.o' failed
make[3]: *** [src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/ahotn_kernel_module.f90.o] Error 1
src/CMakeFiles/pyne.dir/build.make:414: recipe for target 'src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/ahotn_kernel_module.f90.o.provides' failed
make[2]: *** [src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/ahotn_kernel_module.f90.o.provides] Error 2
CMakeFiles/Makefile2:122: recipe for target 'src/CMakeFiles/pyne.dir/all' failed
make[1]: *** [src/CMakeFiles/pyne.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

--------------------

If you are having issues building pyne, please report your problem to pyne-dev@googlegroups.com or look for help at http://pyne.io

--------------------
Traceback (most recent call last):
  File "setup.py", line 449, in <module>
    main()
  File "setup.py", line 421, in main
    main_safe(cmake_args, make_args)
  File "setup.py", line 413, in main_safe
    main_body(cmake_args, make_args)
  File "setup.py", line 393, in main_body
    rtn = subprocess.check_call(['make'] + make_args, cwd='build')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2
ubuntu@ubuntu:~/Downloads/pyne-0.5.0$ 
```
</details>

**Comment by skc222** [comment]
Also the tar.gz link on http://pyne.io/install/linux_source.html#linux-source is of older version of pyne. 
After installing this version, scripts/nuc_data_make command is giving following error:
<details>
<summary> Details </summary>

```
ubuntu@ubuntu:~/Downloads/pyne-pyne-89d5f5d$ scripts/nuc_data_make
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/api.py:5: VnVWarning: pyne.nucname is not yet V&V compliant.
  from .nucname import id, name
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/ensdf.py:10: VnVWarning: pyne.rxname is not yet V&V compliant.
  from pyne import nucname, rxname, data
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/ensdf.py:10: VnVWarning: pyne.data is not yet V&V compliant.
  from pyne import nucname, rxname, data
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/ensdf.py:16: VnVWarning: pyne.ensdf is not yet V&V compliant.
  warn(__name__ + " is not yet V&V compliant.", VnVWarning)
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/decay.py:20: VnVWarning: pyne.dbgen.decay is not yet V&V compliant.
  warn(__name__ + " is not yet V&V compliant.", VnVWarning)
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/isotopic_abundance.py:7: VnVWarning: pyne.dbgen.isotopic_abundance is not yet V&V compliant.
  warn(__name__ + " is not yet V&V compliant.", VnVWarning)
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/atomic_mass.py:16: VnVWarning: pyne.dbgen.atomic_mass is not yet V&V compliant.
  warn(__name__ + " is not yet V&V compliant.", VnVWarning)
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/materials_library.py:20: VnVWarning: pyne.material is not yet V&V compliant.
  from ..material import Material
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/materials_library.py:22: VnVWarning: pyne.dbgen.materials_library is not yet V&V compliant.
  warn(__name__ + " is not yet V&V compliant.", VnVWarning)
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/scattering_lengths.py:23: VnVWarning: pyne.dbgen.scattering_lengths is not yet V&V compliant.
  warn(__name__ + " is not yet V&V compliant.", VnVWarning)
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/kaeri.py:17: VnVWarning: pyne.dbgen.kaeri is not yet V&V compliant.
  warn(__name__ + " is not yet V&V compliant.", VnVWarning)
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/simple_xs.py:21: VnVWarning: pyne.dbgen.simple_xs is not yet V&V compliant.
  warn(__name__ + " is not yet V&V compliant.", VnVWarning)
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/q_val.py:21: VnVWarning: pyne.dbgen.q_val is not yet V&V compliant.
  warn(__name__ + " is not yet V&V compliant.", VnVWarning)
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/cinder.py:22: VnVWarning: pyne.dbgen.cinder is not yet V&V compliant.
  warn(__name__ + " is not yet V&V compliant.", VnVWarning)
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/eaf.py:23: VnVWarning: pyne.dbgen.eaf is not yet V&V compliant.
  warn(__name__ + " is not yet V&V compliant.", VnVWarning)
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/wimsdfpy.py:43: VnVWarning: pyne.dbgen.wimsdfpy is not yet V&V compliant.
  warn(__name__ + " is not yet V&V compliant.", VnVWarning)
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/ndsfpy.py:38: VnVWarning: pyne.dbgen.ndsfpy is not yet V&V compliant.
  warn(__name__ + " is not yet V&V compliant.", VnVWarning)
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/hashtools.py:13: VnVWarning: pyne.dbgen.hashtools is not yet V&V compliant.
  warn(__name__ + " is not yet V&V compliant.", VnVWarning)
/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/nuc_data_make.py:29: VnVWarning: pyne.dbgen.nuc_data_make is not yet V&V compliant.
  warn(__name__ + " is not yet V&V compliant.", VnVWarning)

                                  /   \       
 _                        )      ((   ))     (                          
(@)                      /|\      ))_((     /|\                          
|-|                     / | \    (/\|/\)   / | \                      (@) 
| | -------------------/--|-voV---\`|'/--Vov-|--\---------------------|-|
|-|                         '^`   (o o)  '^`                          | |
| |                               `\Y/'                               |-|
|-|                                                                   | |
| |        /\             ___           __  __             /\         |-|
|-|       /^~\           / _ \_   _  /\ \ \/__\           /^~\        | |  
| |       /^~\          / /_)/ | | |/  \/ /_\             /^~\        |-|
|-|       /^~\         / ___/| |_| / /\  //__             /^~\        | | 
| |       ^||`         \/     \__, \_\ \/\__/             ^||`        |-|  
|-|        ||                |____/                        ||         | | 
| |       ====                                            ====        |-|
|-|                                                                   | |
| |                                                                   |-|
|-|___________________________________________________________________| |
(@)              l   /\ /         ( (       \ /\   l                `\|-|
                 l /   V           \ \       V   \ l                  (@)
                 l/                _) )_          \I                   
                                   `\ /'
                                     `  

Fetching pre-built nuc_data.h5 from http://data.pyne.io/prebuilt_nuc_data.h5
Making nuc_data at /home/ubuntu/.local/lib/python2.7/site-packages/pyne/nuc_data.h5
skipping atomic mass data table creation; already exists.
skipping scattering lengths data table creation; already exists.
skipping ENSDF decay data table creation; already exists.
skipping simple XS data table creation; already exists.
DATAPATH not defined in environment; cinder.dat not found - skipping.
skipping materials library data table creation; already exists.
Grabbing q_values...
Making q_value table...
Grabbing the EAF activation data from IAEA
build_nuc_data/EAF created
  grabbing fendlg-2.0_175-gz and placing it in build_nuc_data/EAF/fendlg-2.0_175-gz
  could not get fendlg-2.0_175-gz from IAEA; trying S3 mirror
Traceback (most recent call last):
  File "scripts/nuc_data_make", line 6, in <module>
    main()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/nuc_data_make.py", line 155, in main
    make_map[mo](args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/eaf.py", line 261, in make_eaf
    grabbed = grab_eaf_data(build_dir)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyne/dbgen/eaf.py", line 56, in grab_eaf_data
    urllib.urlretrieve(s3_base_url + eaf_gzip, fpath)
NameError: global name 's3_base_url' is not defined
```
</details>

**Comment by skc222** [comment]
@katyhuff 
I was able to resolve installation error issue by some minor changes in pyne-0.5.0/src/transport_spatial_methods/3d/ahotn_kernel_module.f90 i.e. by truncating line using '&'

But scripts/nuc_data_make command is giving following error:

```
Grabbing Atomic data from NNDC
Making atomic decay data table
skipping simple XS data table creation; already exists.
DATAPATH not defined in environment; cinder.dat not found - skipping.
skipping materials library data table creation; already exists.
skipping q_value table creation; already exists.
skipping creation of dose factor tables; already exists.
Grabbing the EAF activation data from IAEA
build_nuc_data/EAF created
  grabbing fendlg-2.0_175-gz and placing it in build_nuc_data/EAF/fendlg-2.0_175-gz
  could not get fendlg-2.0_175-gz from IAEA; trying S3 mirror
Traceback (most recent call last):
  File "scripts/nuc_data_make", line 6, in <module>
    main()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/dbgen/nuc_data_make.py", line 157, in main
    make_map[mo](args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/dbgen/eaf.py", line 261, in make_eaf
    grabbed = grab_eaf_data(build_dir)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/dbgen/eaf.py", line 56, in grab_eaf_data
    urllib.urlretrieve(s3_base_url + eaf_gzip, fpath)
NameError: global name 's3_base_url' is not defined
```

**Comment by katyhuff** [comment]
I believe we discussed the s3_base_url problem on friday and decided that bug was due to an out of date tar.gz zipped source code download. Version 0.5 still retains this bug, but the most recent development branch does not. 

Anyway, the issue is that all instances of s3_base_url, in pyne/pyne/dbgen/eaf.py should be cf_base_url.  This has already been fixed in the most recent version of the eaf.py file: https://github.com/pyne/pyne/blob/develop/pyne/dbgen/eaf.py . 

Regarding the original issue: Can you show what you mean by "i.e. by truncating line using '&'" ? The line, as I currently see it in my version of the code, is truncated with & already. https://github.com/pyne/pyne/blob/develop/src/transport_spatial_methods/3d/ahotn_kernel_module.f90

I think you should be trying to build pyne from the most recent develop branch -- it's clear that past versions have issues. I don't recall why you were starting with the zipped releases rather than the current code. Was there a reason for that?

**Comment by skc222** [comment]
Actually I remember that you said, .tar.gz on https://github.com/pyne/pyne/releases/tag/0.5.0 is the most recent version and I should be changing links for tar.gz on http://pyne.io/install/linux_source.html#linux-source to this. So I tried installing to check if there is any error before actually adding it to documentation. But it seems that it is also not up to date as there is no  '&' used.

**Comment by katyhuff** [comment]
The 0.5.0 release is not the most recent develop branch. 

- Current Develop: 5 days ago
- 0.5.3 : 14 days ago 
- 0.5.3: 15 days ago 
- 0.5.1: Oct 3, 2016 
- 0.5.0: Apr 29, 2015
- 0.4.0: May 12, 2014

**Comment by skc222** [comment]
Oh okay actually the "latest release" tag is on 0.5.0 so I didn't see the newer releases.
