### ISSUE TITLE
Installation error in file pyne/src/ensdf_processing/GTOL/gtol.f

### ISSUE THREAD

**Issue by andrewryh** [pyne/pyne#893]
Hello everyone.

Try to install PyNE on a cluster. I have installed all dependents EXCEPT MOAB&PyTABS because I don't plan use mesh-features.
After: 
`python setup.py install --user`
I got next error:
```[ 35%] Building Fortran object src/CMakeFiles/gtol.dir/ensdf_processing/GTOL/gtol.f.o
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:4525.27:

               Call Cnvs2u(TRIM(sx),TRIM(sdx),y,dy)                     
                           1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:4529.27:

               Call Cnvs2u(TRIM(sx),sdx,y,dy)                           
                           1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:3646.36:

               WRITE(rpt,'(92X,2A)') TRIM(st1),' - Ignoring gammas'     
                                    1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:3668.36:

               WRITE(rpt,'(92X,2A)') TRIM(st1),' - Ignoring gammas'     
                                    1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:3197.34:

                  WRITE(rpt,'(A)') TRIM(outline)                        
                                  1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:3208.34:

                  WRITE(rpt,'(A)') TRIM(outline)                        
                                  1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:3219.34:

                  WRITE(rpt,'(A)') TRIM(outline)                        
                                  1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:3265.37:

                     WRITE(rpt,'(A)') TRIM(outline)                     
                                     1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:3284.37:

                     WRITE(rpt,'(A)') TRIM(outline)                     
                                     1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:3292.34:

                  WRITE(rpt,'(A)') TRIM(outline)                        
                                  1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:3302.34:

                  WRITE(rpt,'(A)') TRIM(outline)                        
                                  1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:3328.34:

                  WRITE(rpt,'(A)') TRIM(outline)                        
                                  1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:3343.34:

                  WRITE(rpt,'(A)') TRIM(outline)                        
                                  1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:3351.31:

               WRITE(rpt,'(A)') TRIM(outline)                           
                               1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:3361.34:

                  WRITE(rpt,'(A)') TRIM(outline)                        
                                  1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:3366.34:

                  WRITE(rpt,'(A)') TRIM(outline)                        
                                  1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:3396.25:

         WRITE(rpt,'(A)') TRIM(outline)                                 
                         1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:2763.42:

                        IF(INDEXF(CARd,10,TRIM(flstr1)).GT.0) THEN      
                                          1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:2765.44:

                           CALL REPSTR(CARd,TRIM(flstr1),TRIM(flstr2))  
                                            1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:1236.28:

            WRITE(rpt,'(A)') TRIM(outline)                              
                            1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:800.37:

     &           'INPUT FILE (DEF: ',TRIM(file(1)),'):        '         
                                     1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:814.38:

     &           'REPORT FILE (DEF: ',TRIM(file(2)),'):       '         
                                      1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:833.53:

     &         'Enter OUTPUT ENDSF FILE NAME (DEF: ',TRIM(file(3)),'): '
                                                     1
Error: Function 'trim' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:900.23:

      WRITE(rpt,'(/A)') REPEAT('*',lver)                                
                       1
Error: Function 'repeat' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
/home/andreir2/git/pyne/src/ensdf_processing/GTOL/gtol.f:902.22:

      WRITE(rpt,'(A)') REPEAT('*',lver)                                 
                      1
Error: Function 'repeat' is declared CHARACTER(*) and cannot be used at (1) since it is not a dummy argument
Fatal Error: Error count reached limit of 25.
make[2]: *** [src/CMakeFiles/gtol.dir/ensdf_processing/GTOL/gtol.f.o] Error 1
make[1]: *** [src/CMakeFiles/gtol.dir/all] Error 2
make: *** [all] Error 2

--------------------

If you are having issues building pyne, please report your problem to pyne-dev@googlegroups.com or look for help at http://pyne.io

--------------------
Traceback (most recent call last):
  File "setup.py", line 522, in <module>
    main()
  File "setup.py", line 493, in main
    main_safe(cmake_args, make_args)
  File "setup.py", line 485, in main_safe
    main_body(cmake_args, make_args)
  File "setup.py", line 465, in main_body
    rtn = subprocess.check_call(['make'] + make_args, cwd='build')
  File "/usr/local/python/2.7.8/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2
```
I feel like something wrong with gfortran but can't fix it.
I uploaded next modules (module list):`python/2.7.8   gcc/4.9.2      cmake/3.6.2`
Python modules:
```pip freeze
atomicfile==1.0
cffi==1.2.1
cryptography==1.0.1
Cython==0.22
DendroPy==3.12.2
enum34==1.0.4
h5py==2.7.0
HTSeq===0.6.1p1
idna==2.0
ipaddress==1.0.14
ipython==2.2.0
matplotlib==1.4.0
mock==1.0.1
monty==0.6.5
mpi4py==1.3.1
nltk==3.0.0
nose==1.3.4
numexpr==2.4
numpy==1.9.2
pandas==0.15.2
petsc4py==3.5.1
prettytable==0.7.2
pyasn1==0.1.8
pybtex==0.18
pycparser==2.14
Pygments==1.6
pyhull==1.5.4
pymatgen==3.2.1
pyOpenSSL==0.15.1
pyparsing==2.0.2
python-dateutil==2.2
pytz==2014.10
PyVTK==0.4.85
PyYAML==3.11
requests==2.7.0
scipy==0.16.0
six==1.9.0
sympy==0.7.5
tables==3.1.1
textblob==0.9.0
textmining==1.0
```

Any ideas how fix this?

Thank you

**Comment by ljacobson64** [comment]
What version of gfortran are you using?

EDIT: I didn't read very closely, looks like you're using 4.9.2

**Comment by andrewryh** [comment]
I using gcc/4.9.2, as I understand - gfortran is the part of GCC.

Is it very old? I have tried gcc/6.2.0 but it didn't change anything...

**Comment by ljacobson64** [comment]
Can you confirm that it's actually loading gfortran 4.9 when you compile? I was able to reproduce your exact errors when compiling with gfortran 4.4, but 4.6 and above compile correctly.

**Comment by andrewryh** [comment]
```
$ gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/software/GCC/4.9.2/libexec/gcc/x86_64-unknown-linux-gnu/4.9.2/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../configure --enable-languages=c,c++,fortran,lto --enable-lto --enable-checking=release --disable-multilib --enable-shared=yes --enable-static=yes --enable-threads=posix --enable-gold=default --enable-plugins --enable-ld --with-plugin-ld=ld.gold --enable-bootstrap --prefix=/usr/local/software/GCC/4.9.2 --with-local-prefix=/usr/local/software/GCC/4.9.2
Thread model: posix
gcc version 4.9.2 (GCC) 
```

So, it is definitely gfortran 4.9

**Comment by andrewryh** [comment]
Just tried it with GCC-6.2.0 and got the same error...

**Comment by ljacobson64** [comment]
Hmm, I'm running out of ideas then. Could you copy some of the output from running `setup.py install --user` here? The first few lines should be sufficient. For me it looks like

```
lucas@zapdos:~/build/pyne$ python setup.py install --user
    ****stuff****
-- The Fortran compiler identification is GNU 4.9.4
-- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.9.4
    ****stuff****
```

It could be the case that setup.py isn't noticing that you have gcc 4.9 and is instead trying to use an older compiler.

**Comment by andrewryh** [comment]
Sorry, my bad:

```
$ python setup.py install --user
/usr/local/cmake/3.6.2/bin/cmake
CMake command is
cmake .. -DHAVE_SETUPTOOLS=TRUE -DPYTHON_EXECUTABLE=/usr/local/python/2.7.8/bin/python
-- CMAKE_Fortran_IMPLICIT_LINK_DIRECTORIES = /usr/local/software/GCC/4.9.2/lib64;/usr/lib/gcc/x86_64-redhat-linux/4.4.7;/usr/lib64;/lib64;/usr/local/software/GCC/4.9.2/lib;/usr/lib
-- CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES = gfortranbegin;gfortran;m;c
-- Build type: Release
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5_LIBRARY_DIRS = /usr/lib64
-- PYTHON_EXECUTABLE: /usr/local/python/2.7.8/bin/python
-- Could NOT find MOAB (missing:  MOAB_LIBRARY MOAB_INCLUDE_DIR) 
-- MOAB Found: FALSE
-- Cython Version: Cython version 0.22
-- Pyne platform defined as: __LINUX__
CMAKE_Fortran_COMPILER full path: /usr/bin/f95
Fortran compiler: f95
No optimized Fortran compiler flags are known, we just try -fpic...

                                  /   \       
                          )      ((   ))     (                          
(@)                      /|\      ))_((     /|\                          
|-|                     / | \    (/\|/\)   / | \                      (@) 
| | -------------------/--|-voV---\`|'/--Vov-|--\---------------------|-|
|-|                         '^`   (o o)  '^`                          | |
| |                               `\Y/'                               |-|
|-|                                                                   | |
| |        /\             ___           __  __             /\         |-|
|-|       /^~\           / _ \_   _  /\ \ \/__\           /^~\        | |  
| |       /^~\          / /_)/ | | |/  \/ /_\             /^~\        |-|
|-|       /^~\         / ___/| |_| / /\  //__             /^~\        | | 
| |       ^||`         \/     \__, \_\ \/\__/             ^||`        |-|  
|-|        ||                |____/                        ||         | | 
| |       ====                                            ====        |-|
|-|                                                                   | |
| |                                                                   |-|
|-|___________________________________________________________________| |
(@)              l   /\ /         ( (       \ /\   l                `\|-|
                 l /   V           \ \       V   \ l                  (@)
                 l/                _) )_          \I                   
                                   `\ /'
                                     `  


-- CMake Install Prefix: /usr/local
-- RPATH: $ORIGIN/../lib
-- NUMPY_VERSION_STRING = 1.9.2
-- Include paths for /projects/arfc/pyne/pyne/src: /usr/include;/usr/local/python/2.7.8/lib/python2.7/site-packages/numpy/core/include;/projects/arfc/pyne/pyne/src
-- Include paths for /projects/arfc/pyne/pyne/pyne: /usr/include;/usr/local/python/2.7.8/lib/python2.7/site-packages/numpy/core/include;/projects/arfc/pyne/pyne/src
CMake Warning (dev) at pyne/CMakeLists.txt:157 (target_link_libraries):
  Policy CMP0039 is not set: Utility targets may not have link dependencies.
  Run "cmake --help-policy CMP0039" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Utility target "transport_spatial_methods" should not be used as the target
  of a target_link_libraries call.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Include paths for /projects/arfc/pyne/pyne/pyne/xs: /usr/include;/usr/local/python/2.7.8/lib/python2.7/site-packages/numpy/core/include;/projects/arfc/pyne/pyne/src;/usr/local/python/2.7.8/include/python2.7
-- Include paths for /projects/arfc/pyne/pyne: /usr/include;/usr/local/python/2.7.8/lib/python2.7/site-packages/numpy/core/include
-- Copying C/C++ header files.
-- Copying Cython header files.
-- Copying scripts.
-- Configuring done
-- Generating done
-- Build files have been written to: /projects/arfc/pyne/pyne/build
[  0%] Built target ReplicatePythonSourceTree
[ 37%] Built target pyne
[ 40%] Built target alphad
[ 42%] Built target bldhst
[ 45%] Built target hsmrg
[ 47%] Built target hsicc
[ 49%] Built target delta
[ 51%] Built target seqhst
[ 52%] Building Fortran object src/CMakeFiles/gtol.dir/ensdf_processing/GTOL/gtol.f.o

```

**Comment by ljacobson64** [comment]
Can you delete the `build` directory and try it again

**Comment by andrewryh** [comment]
Sorry, my bad

```

$ python setup.py install --user
/usr/local/cmake/3.6.2/bin/cmake
CMake command is
cmake .. -DHAVE_SETUPTOOLS=TRUE -DPYTHON_EXECUTABLE=/usr/local/python/2.7.8/bin/python
-- The Fortran compiler identification is GNU 4.4.7
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
-- Check for working C compiler: /usr/local/software/GCC/4.9.2/bin/gcc
-- Check for working C compiler: /usr/local/software/GCC/4.9.2/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/software/GCC/4.9.2/bin/c++
-- Check for working CXX compiler: /usr/local/software/GCC/4.9.2/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_Fortran_IMPLICIT_LINK_DIRECTORIES = /usr/local/software/GCC/4.9.2/lib64;/usr/lib/gcc/x86_64-redhat-linux/4.4.7;/usr/lib64;/lib64;/usr/local/software/GCC/4.9.2/lib;/usr/lib
-- CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES = gfortranbegin;gfortran;m;c
-- Build type: Release
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib64/libhdf5.so;/usr/lib64/libz.so;/usr/lib64/libm.so (found version "1.8.5.1") found components:  C 
-- HDF5_LIBRARY_DIRS = /usr/lib64
-- Found PythonInterp: /usr/local/python/2.7.8/bin/python (found version "2.7.8") 
-- Found PythonLibs: /usr/local/python/2.7.8/lib/libpython2.7.so
-- PYTHON_EXECUTABLE: /usr/local/python/2.7.8/bin/python
-- Could NOT find MOAB (missing:  MOAB_LIBRARY MOAB_INCLUDE_DIR) 
-- MOAB Found: FALSE
-- Found Cython: /usr/local/python/2.7.8/bin/cython  
-- Cython Version: Cython version 0.22
-- Pyne platform defined as: __LINUX__
CMAKE_Fortran_COMPILER full path: /usr/bin/f95
Fortran compiler: f95
No optimized Fortran compiler flags are known, we just try -fpic...

                                  /   \       
                          )      ((   ))     (                          
(@)                      /|\      ))_((     /|\                          
|-|                     / | \    (/\|/\)   / | \                      (@) 
| | -------------------/--|-voV---\`|'/--Vov-|--\---------------------|-|
|-|                         '^`   (o o)  '^`                          | |
| |                               `\Y/'                               |-|
|-|                                                                   | |
| |        /\             ___           __  __             /\         |-|
|-|       /^~\           / _ \_   _  /\ \ \/__\           /^~\        | |  
| |       /^~\          / /_)/ | | |/  \/ /_\             /^~\        |-|
|-|       /^~\         / ___/| |_| / /\  //__             /^~\        | | 
| |       ^||`         \/     \__, \_\ \/\__/             ^||`        |-|  
|-|        ||                |____/                        ||         | | 
| |       ====                                            ====        |-|
|-|                                                                   | |
| |                                                                   |-|
|-|___________________________________________________________________| |
(@)              l   /\ /         ( (       \ /\   l                `\|-|
                 l /   V           \ \       V   \ l                  (@)
                 l/                _) )_          \I                   
                                   `\ /'
                                     `  


-- CMake Install Prefix: /usr/local
-- RPATH: $ORIGIN/../lib
-- NUMPY_VERSION_STRING = 1.9.2
-- Found Numpy: 1.9.2  
-- Include paths for /projects/arfc/pyne/pyne/src: /usr/include;/usr/local/python/2.7.8/lib/python2.7/site-packages/numpy/core/include;/projects/arfc/pyne/pyne/src
-- Include paths for /projects/arfc/pyne/pyne/pyne: /usr/include;/usr/local/python/2.7.8/lib/python2.7/site-packages/numpy/core/include;/projects/arfc/pyne/pyne/src
CMake Warning (dev) at pyne/CMakeLists.txt:157 (target_link_libraries):
  Policy CMP0039 is not set: Utility targets may not have link dependencies.
  Run "cmake --help-policy CMP0039" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Utility target "transport_spatial_methods" should not be used as the target
  of a target_link_libraries call.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Include paths for /projects/arfc/pyne/pyne/pyne/xs: /usr/include;/usr/local/python/2.7.8/lib/python2.7/site-packages/numpy/core/include;/projects/arfc/pyne/pyne/src;/usr/local/python/2.7.8/include/python2.7
-- Include paths for /projects/arfc/pyne/pyne: /usr/include;/usr/local/python/2.7.8/lib/python2.7/site-packages/numpy/core/include
-- Copying C/C++ header files.
-- Copying Cython header files.
-- Copying scripts.
-- Configuring done
-- Generating done
-- Build files have been written to: /projects/arfc/pyne/pyne/build
Scanning dependencies of target ReplicatePythonSourceTree
[  0%] Built target ReplicatePythonSourceTree
Scanning dependencies of target pyne
[  0%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/precision_module.f90.o
[  1%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/invar.f90.o
[  2%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/solvar.f90.o
[  3%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/geompack.f90.o
[  4%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/trackstruct.f90.o
[  5%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/timevar.f90.o
[  6%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/igeompack.f90.o
[  6%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/trackroutines.f90.o
[  7%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/sct_module.f90.o
[  8%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/dgfem_kernel.f90.o
[  9%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/ahotn_kernel_module.f90.o
[ 10%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/sct_step_kernel_module.f90.o
[ 11%] Building CXX object src/CMakeFiles/pyne.dir/atomic_data.cpp.o
[ 12%] Building CXX object src/CMakeFiles/pyne.dir/data.cpp.o
[ 12%] Building CXX object src/CMakeFiles/pyne.dir/decay.cpp.o
[ 13%] Building CXX object src/CMakeFiles/pyne.dir/enrichment.cpp.o
[ 14%] Building CXX object src/CMakeFiles/pyne.dir/enrichment_cascade.cpp.o
[ 15%] Building CXX object src/CMakeFiles/pyne.dir/enrichment_symbolic.cpp.o
[ 16%] Building CXX object src/CMakeFiles/pyne.dir/jsoncpp.cpp.o
[ 16%] Building CXX object src/CMakeFiles/pyne.dir/jsoncustomwriter.cpp.o
[ 17%] Building CXX object src/CMakeFiles/pyne.dir/material.cpp.o
[ 18%] Building CXX object src/CMakeFiles/pyne.dir/nucname.cpp.o
[ 19%] Building CXX object src/CMakeFiles/pyne.dir/particle.cpp.o
[ 20%] Building CXX object src/CMakeFiles/pyne.dir/rxname.cpp.o
[ 20%] Building CXX object src/CMakeFiles/pyne.dir/tally.cpp.o
[ 21%] Building CXX object src/CMakeFiles/pyne.dir/utils.cpp.o
[ 22%] Building Fortran object src/CMakeFiles/pyne.dir/endftod.f90.o
[ 23%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/angle.f90.o
[ 23%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/check.f90.o
[ 24%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/echo.f90.o
[ 24%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/inner.f90.o
[ 25%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/output.f90.o
[ 26%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/output_phi.f90.o
[ 27%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/p.f90.o
[ 28%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/read_inflow_ahotn.f90.o
[ 29%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/read_inflow_dgfem.f90.o
[ 30%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/read_inflow_sct_step.f90.o
[ 31%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/readsrc.f90.o
[ 31%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/readxs.f90.o
[ 32%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/solve.f90.o
[ 32%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/sweep_ahotn_l.f90.o
[ 33%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/sweep_ahotn_nefd.f90.o
[ 34%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/sweep_dgfem.f90.o
[ 35%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/sweep_sct_step.f90.o
[ 36%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/version.f90.o
[ 37%] Linking CXX shared library libpyne.so
[ 37%] Built target pyne
Scanning dependencies of target alphad
[ 38%] Building Fortran object src/CMakeFiles/alphad.dir/ensdf_processing/ALPHAD/alphad.f.o
[ 39%] Building Fortran object src/CMakeFiles/alphad.dir/ensdf_processing/nsdflib95.f.o
[ 40%] Linking Fortran executable alphad
[ 40%] Built target alphad
Scanning dependencies of target bldhst
[ 41%] Building Fortran object src/CMakeFiles/bldhst.dir/ensdf_processing/HSICC/bldhst.for.o
[ 42%] Linking Fortran executable bldhst
[ 42%] Built target bldhst
Scanning dependencies of target hsmrg
[ 43%] Building Fortran object src/CMakeFiles/hsmrg.dir/ensdf_processing/HSICC/hsmrg.for.o
[ 44%] Building Fortran object src/CMakeFiles/hsmrg.dir/ensdf_processing/nsdflib95.f.o
[ 45%] Linking Fortran executable hsmrg
[ 45%] Built target hsmrg
Scanning dependencies of target hsicc
[ 46%] Building Fortran object src/CMakeFiles/hsicc.dir/ensdf_processing/HSICC/hsicc.for.o
[ 46%] Building Fortran object src/CMakeFiles/hsicc.dir/ensdf_processing/nsdflib95.f.o
[ 47%] Linking Fortran executable hsicc
[ 47%] Built target hsicc
Scanning dependencies of target delta
[ 48%] Building Fortran object src/CMakeFiles/delta.dir/ensdf_processing/DELTA/delta.for.o
```



So, it is seen Fortran compiler only 4.4.7 by some mistery...

**Comment by andrewryh** [comment]
Looks like Cmake detect wrong gfortran way

**Comment by ljacobson64** [comment]
Try this

```
rm -rf build
python setup.py -DCMAKE_Fortran_COMPILER=<path_to_gfortran_4.9> install --user
```

**Comment by andrewryh** [comment]
@ljacobson64 thank you, it works!

```
$ which gfortran
/usr/local/software/GCC/4.9.2/bin/gfortran
rm -rf build/
$ python setup.py -DCMAKE_Fortran_COMPILER=/usr/local/software/GCC/4.9.2/bin/gfortran install --user
/usr/local/cmake/3.6.2/bin/cmake
CMake command is
cmake .. -DCMAKE_Fortran_COMPILER=/usr/local/software/GCC/4.9.2/bin/gfortran -DHAVE_SETUPTOOLS=TRUE -DPYTHON_EXECUTABLE=/usr/local/python/2.7.8/bin/python
-- The Fortran compiler identification is GNU 4.9.2
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working Fortran compiler: /usr/local/software/GCC/4.9.2/bin/gfortran
-- Check for working Fortran compiler: /usr/local/software/GCC/4.9.2/bin/gfortran  -- works
```
