### ISSUE TITLE
Error building on Mac OS X: Cannot determine link language for target

### ISSUE THREAD

**Issue by asmeurer** [pyne/pyne#911]
```
$./setup.py build
/Users/aaronmeurer/anaconda3/bin/cmake
CMake command is
cmake .. -DCMAKE_INSTALL_PREFIX=/Users/aaronmeurer/anaconda3 -DPYTHON_EXECUTABLE=/Users/aaronmeurer/anaconda3/bin/python
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /Users/aaronmeurer/anaconda3/bin/cc
-- Check for working C compiler: /Users/aaronmeurer/anaconda3/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /Users/aaronmeurer/anaconda3/bin/c++
-- Check for working CXX compiler: /Users/aaronmeurer/anaconda3/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

                                  /   \
                          )      ((   ))     (
(@)                      /|\      ))_((     /|\
|-|                     / | \    (/\|/\)   / | \                      (@)
| | -------------------/--|-voV---\`|'/--Vov-|--\---------------------|-|
|-|                         '^`   (o o)  '^`                          | |
| |                               `\Y/'                               |-|
|-|                                                                   | |
| |        /\             ___           __  __             /\         |-|
|-|       /^~\           / _ \_   _  /\ \ \/__\           /^~\        | |
| |       /^~\          / /_)/ | | |/  \/ /_\             /^~\        |-|
|-|       /^~\         / ___/| |_| / /\  //__             /^~\        | |
| |       ^||`         \/     \__, \_\ \/\__/             ^||`        |-|
|-|        ||                |____/                        ||         | |
| |       ====                                            ====        |-|
|-|                                                                   | |
| |                                                                   |-|
|-|___________________________________________________________________| |
(@)              l   /\ /         ( (       \ /\   l                `\|-|
                 l /   V           \ \       V   \ l                  (@)
                 l/                _) )_          \I
                                   `\ /'
                                     `


-- Pyne platform defined as: __APPLE__
-- Build type: Release
-- CMAKE_INSTALL_RPATH: /Users/aaronmeurer/anaconda3/lib:/Users/aaronmeurer/anaconda3/lib
-- CMake Install Prefix: /Users/aaronmeurer/anaconda3
-- Dependency Root Dir (DEPS_ROOT_DIR): /Users/aaronmeurer/anaconda3
-- Dependency Hints (DEPS_HINTS): HINTS;/Users/aaronmeurer/anaconda3
-- Dependency Binary Hints (DEPS_BIN_HINTS): HINTS;/Users/aaronmeurer/anaconda3;/Users/aaronmeurer/anaconda3/bin
-- Dependency Library Hints (DEPS_LIB_HINTS): HINTS;/Users/aaronmeurer/anaconda3;/Users/aaronmeurer/anaconda3/lib
-- Dependency Include Hints (DEPS_INCLUDE_HINTS): HINTS;/Users/aaronmeurer/anaconda3/include
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
--    HDF5 Root:
--    HDF5 Include directory: /Users/aaronmeurer/anaconda/include
--    HDF5 Library directories:
--    HDF5 Libraries: /Users/aaronmeurer/anaconda/lib/libhdf5.dylib;/usr/lib/libc++.dylib;/usr/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib
--    HDF5 High Level Libraries: /Users/aaronmeurer/anaconda/lib/libhdf5_hl.dylib
-- Could NOT find MOAB (missing: MOAB_INCLUDE_DIR)
-- MOAB Found: FALSE
-- PYTHON_EXECUTABLE: /Users/aaronmeurer/anaconda3/bin/python
-- PYTHON_SITE_PACKAGES: /Users/aaronmeurer/anaconda3/lib/python3.5/site-packages
-- NUMPY_VERSION_STRING = 1.11.3
-- LIBS: /Users/aaronmeurer/anaconda/lib/libhdf5.dylib;/usr/lib/libc++.dylib;/usr/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib;/Users/aaronmeurer/anaconda/lib/libhdf5_hl.dylib;/Users/aaronmeurer/anaconda3/lib/libpython3.5m.dylib
-- Include paths for /Users/aaronmeurer/Documents/pyne/src: /Users/aaronmeurer/anaconda/include;/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numpy/core/include;/Users/aaronmeurer/Documents/pyne/build/pyne;/Users/aaronmeurer/Documents/pyne/src
-- Include paths for /Users/aaronmeurer/Documents/pyne/pyne: /Users/aaronmeurer/anaconda/include;/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numpy/core/include;/Users/aaronmeurer/Documents/pyne/build/pyne;/Users/aaronmeurer/Documents/pyne/src
-- Modules to Cythonize: ace;bins;data;dtypes;endf;enrichment;extra_types;jsoncpp;material;nucname;particle;pyne_config;rxname;stlcontainers;tally;transmuters;_utils
-- F2PY F90 FLAGS:
-- Include paths for /Users/aaronmeurer/Documents/pyne/pyne/xs: /Users/aaronmeurer/anaconda/include;/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numpy/core/include;/Users/aaronmeurer/Documents/pyne/build/pyne;/Users/aaronmeurer/Documents/pyne/src
-- Configuring done
CMake Error: CMake can not determine linker language for target: gtol
CMake Error: Cannot determine link language for target "gtol".
CMake Error: CMake can not determine linker language for target: seqhst
CMake Error: Cannot determine link language for target "seqhst".
CMake Error: CMake can not determine linker language for target: hsicc
CMake Error: Cannot determine link language for target "hsicc".
CMake Error: CMake can not determine linker language for target: bldhst
CMake Error: Cannot determine link language for target "bldhst".
CMake Error: CMake can not determine linker language for target: radd
CMake Error: Cannot determine link language for target "radd".
CMake Error: CMake can not determine linker language for target: delta
CMake Error: Cannot determine link language for target "delta".
CMake Error: CMake can not determine linker language for target: alphad
CMake Error: Cannot determine link language for target "alphad".
CMake Error: CMake can not determine linker language for target: logft
CMake Error: Cannot determine link language for target "logft".
CMake Error: CMake can not determine linker language for target: ruler
CMake Error: Cannot determine link language for target "ruler".
CMake Error: CMake can not determine linker language for target: hsmrg
CMake Error: Cannot determine link language for target "hsmrg".
-- Generating done
-- Build files have been written to: /Users/aaronmeurer/Documents/pyne/build

--------------------

If you are having issues building pyne, please report your problem to pyne-dev@googlegroups.com or look for help at http://pyne.io

--------------------
Traceback (most recent call last):
  File "./setup.py", line 442, in <module>
    main()
  File "./setup.py", line 415, in main
    main_safe(ns)
  File "./setup.py", line 407, in main_safe
    main_body(ns)
  File "./setup.py", line 389, in main_body
    rtn = subprocess.check_call(cmake_cmd, cwd=ns.build_dir, shell=IS_NT)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '..', '-DCMAKE_INSTALL_PREFIX=/Users/aaronmeurer/anaconda3', '-DPYTHON_EXECUTABLE=/Users/aaronmeurer/anaconda3/bin/python']' returned non-zero exit status 1
```

**Comment by scopatz** [comment]
Hi @asmeurer - thanks for reporting, can you try building with 

`./setup.py install -DBUILD_SPATIAL_SOLVER=FALSE`

This should disable the package that is breaking for you, IIRC.  Note that you may need to add `--clean` or manually remove the build directory before you attempt to build again.

**Comment by asmeurer** [comment]
Same error with that flag, unfortunately.

**Comment by scopatz** [comment]
hmm odd.
